'use strict';

const fs = require('fs');
const path = require('path');
const { EXPECTED, REQUIRED_ENV } = require('../config');
const { missingEnv, summarizeStatus, unique } = require('../utils');
const { readDryRunPlan } = require('../planner/plan-writer');

function sectionForResult(result) {
  const lines = [
    `## ${result.name}`,
    '',
    `Status: **${String(result.status || 'info').toUpperCase()}**`,
    ''
  ];

  if (result.notes && result.notes.length) {
    lines.push('Notes:');
    for (const note of result.notes) {
      lines.push(`- ${note}`);
    }
    lines.push('');
  }

  if (result.inspectedFiles && result.inspectedFiles.length) {
    lines.push('Inspected files:');
    for (const file of result.inspectedFiles) {
      lines.push(`- \`${file}\``);
    }
    lines.push('');
  }

  lines.push('| Check | Status | Details |');
  lines.push('|---|---:|---|');
  for (const check of result.checks || []) {
    const details = check.details || '';
    lines.push(`| ${check.label} | ${String(check.status).toUpperCase()} | ${details.replace(/\|/g, '\\|')} |`);
  }
  lines.push('');

  if (result.futureChecks && result.futureChecks.length) {
    lines.push('Future read-only API checks planned for this module:');
    for (const item of result.futureChecks) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  const missingGroups = [
    ['Missing GA4 custom dimensions', result.missingCustomDimensions],
    ['Missing GA4 key events/conversions', result.missingKeyEvents],
    ['Missing GTM Data Layer Variables', result.missingDlvs],
    ['Missing GTM triggers', result.missingTriggers]
  ].filter(([, items]) => items && items.length);

  for (const [label, items] of missingGroups) {
    lines.push(label + ':');
    for (const item of items) {
      lines.push(`- \`${item}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildMarkdownReport(results, options = {}) {
  const timestamp = options.timestamp || new Date().toISOString();
  const plan = options.plan || null;
  const allChecks = results.flatMap((result) => result.checks || []);
  const summary = summarizeStatus(allChecks);
  const requiredEnvNames = unique(Object.values(REQUIRED_ENV).flat());
  const missingEnvNames = unique([
    ...missingEnv(requiredEnvNames),
    ...results.flatMap((result) => result.missingEnv || [])
  ]);
  const warnings = allChecks
    .filter((check) => check.status === 'warn')
    .map((check) => check.label);
  const missingCustomDimensions = unique(results.flatMap((result) => result.missingCustomDimensions || []));
  const missingKeyEvents = unique(results.flatMap((result) => result.missingKeyEvents || []));
  const missingDlvs = unique(results.flatMap((result) => result.missingDlvs || []));
  const missingTriggers = unique(results.flatMap((result) => result.missingTriggers || []));
  const ga4Result = results.find((result) => result.name === 'GA4 checks');
  const gtmResult = results.find((result) => result.name === 'GTM checks');
  const ga4Evaluated = Boolean(ga4Result && ga4Result.liveApiChecked);
  const gtmEvaluated = Boolean(gtmResult && gtmResult.liveApiChecked);
  const permissionIssues = allChecks
    .filter((check) => /permission|PERMISSION_DENIED|unauthorized|forbidden|HTTP 401|HTTP 403/i.test(`${check.label} ${check.details || ''}`))
    .map((check) => `${check.label}: ${check.details}`);

  const lines = [
    '# CRBOX Marketing Ops Readiness Report',
    '',
    `Generated: ${timestamp}`,
    '',
    `Mode: **${EXPECTED.mode}**`,
    '',
    '> This report is generated by a read-only repository checker scaffold. No GA4, GTM, Google Ads, or Meta platform mutations were performed.',
    '',
    '## Summary',
    '',
    `- Passed checks: ${summary.pass || 0}`,
    `- Warnings: ${summary.warn || 0}`,
    `- Skipped checks: ${summary.skipped || 0}`,
    `- Missing environment variables: ${missingEnvNames.length}`,
    '',
    '## Missing Environment Variables',
    '',
    missingEnvNames.length ? missingEnvNames.map((name) => `- \`${name}\``).join('\n') : '- None detected for the checks that ran.',
    '',
    '## Warnings',
    '',
    warnings.length ? warnings.map((warning) => `- ${warning}`).join('\n') : '- None.',
    '',
    '## Live Platform Gaps',
    '',
    'Missing GA4 custom dimensions:',
    ga4Evaluated
      ? (missingCustomDimensions.length ? missingCustomDimensions.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GA4 live API check did not complete.',
    '',
    'Missing GA4 key events/conversions:',
    ga4Evaluated
      ? (missingKeyEvents.length ? missingKeyEvents.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GA4 live API check did not complete.',
    '',
    'Missing GTM Data Layer Variables:',
    gtmEvaluated
      ? (missingDlvs.length ? missingDlvs.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GTM live API check did not complete.',
    '',
    'Missing GTM triggers:',
    gtmEvaluated
      ? (missingTriggers.length ? missingTriggers.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GTM live API check did not complete.',
    '',
    'Permission or scope issues:',
    permissionIssues.length ? permissionIssues.map((item) => `- ${item}`).join('\n') : '- None detected.',
    '',
    '## Dry-Run Plan Summary',
    '',
    plan
      ? `- Generated: ${plan.generatedAt}
- Mode: ${plan.mode}
- Proposed GA4 actions: ${plan.summary ? plan.summary.totalProposedGa4Actions : 0}
- Proposed GTM actions: ${plan.summary ? plan.summary.totalProposedGtmActions : 0}
- Blocked actions: ${plan.summary ? plan.summary.totalBlockedActions : 0}
- Risk summary: ${plan.summary ? JSON.stringify(plan.summary.riskSummary) : '{}'}
- Mutation performed: ${plan.mutationPerformed}
- Plan files: \`docs/marketing-ops-dry-run-plan.md\`, \`docs/marketing-ops-dry-run-plan.json\``
      : '- No dry-run plan file found yet.',
    '',
    ...results.map(sectionForResult),
    '## Recommended Next Actions',
    '',
    '- Keep this agent in `read_only` mode.',
    '- Add credentials only through environment variables; never commit secrets.',
    '- Use GA4/GTM live checks only to verify state; do not create GTM workspaces, tags, GA4 dimensions, Google Ads conversions, or Meta assets from this version.',
    '',
    '## Mutation Statement',
    '',
    'No platform mutations were performed. This run did not create, update, publish, delete, or mutate GA4, GTM, Google Ads, or Meta objects.'
  ];

  return lines.join('\n') + '\n';
}

function writeMarkdownReport(root, results, options = {}) {
  const outputPath = path.join(root, 'docs', 'marketing-ops-readiness-report.md');
  const markdown = buildMarkdownReport(results, {
    ...options,
    plan: options.plan || readDryRunPlan(root)
  });
  fs.writeFileSync(outputPath, markdown, 'utf8');
  return outputPath;
}

module.exports = {
  buildMarkdownReport,
  writeMarkdownReport
};
