'use strict';

const fs = require('fs');
const path = require('path');
const { EXPECTED, REQUIRED_ENV } = require('../config');
const { missingEnv, summarizeStatus, unique } = require('../utils');
const { readDryRunPlan } = require('../planner/plan-writer');
const { validateDryRunPlan } = require('../apply/apply-validator');
const { readGa4CreateResult } = require('../apply/ga4-create-result');
const { readGtmCreateResult } = require('../apply/gtm-create-result');
const { readPreflight } = require('../gtm-preflight');

function sectionForResult(result) {
  const lines = [
    `## ${result.name}`,
    '',
    `Status: **${String(result.status || 'info').toUpperCase()}**`,
    ''
  ];

  if (result.notes && result.notes.length) {
    lines.push('Notes:');
    for (const note of result.notes) {
      lines.push(`- ${note}`);
    }
    lines.push('');
  }

  if (result.inspectedFiles && result.inspectedFiles.length) {
    lines.push('Inspected files:');
    for (const file of result.inspectedFiles) {
      lines.push(`- \`${file}\``);
    }
    lines.push('');
  }

  lines.push('| Check | Status | Details |');
  lines.push('|---|---:|---|');
  for (const check of result.checks || []) {
    const details = check.details || '';
    lines.push(`| ${check.label} | ${String(check.status).toUpperCase()} | ${details.replace(/\|/g, '\\|')} |`);
  }
  lines.push('');

  if (result.futureChecks && result.futureChecks.length) {
    lines.push('Future read-only API checks planned for this module:');
    for (const item of result.futureChecks) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  const missingGroups = [
    ['Missing GA4 custom dimensions', result.missingCustomDimensions],
    ['Missing GA4 key events/conversions', result.missingKeyEvents],
    ['Missing GTM Data Layer Variables', result.missingDlvs],
    ['Missing GTM triggers', result.missingTriggers]
  ].filter(([, items]) => items && items.length);

  for (const [label, items] of missingGroups) {
    lines.push(label + ':');
    for (const item of items) {
      lines.push(`- \`${item}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function warningSummary(check) {
  const label = check.label || '';
  const details = check.details || '';

  if (/^Missing from /i.test(details) && /\bexists$/i.test(label)) {
    return label.replace(/\bexists$/i, 'missing/not found');
  }

  if (/^No .* found/i.test(details)) {
    if (/appear present or planned$/i.test(label)) {
      return label.replace(/appear present or planned$/i, 'not found or not planned');
    }
    return `${label} not found`;
  }

  return label;
}

function buildMarkdownReport(results, options = {}) {
  const timestamp = options.timestamp || new Date().toISOString();
  const plan = options.plan || null;
  const apply = options.apply || null;
  const ga4CreateResult = options.ga4CreateResult || readGa4CreateResult(options.root || process.cwd());
  const gtmCreateResult = options.gtmCreateResult || readGtmCreateResult(options.root || process.cwd());
  const gtmPreflight = options.gtmPreflight || readPreflight(options.root || process.cwd());
  const allChecks = results.flatMap((result) => result.checks || []);
  const summary = summarizeStatus(allChecks);
  const requiredEnvNames = unique(Object.values(REQUIRED_ENV).flat());
  const missingEnvNames = unique([
    ...missingEnv(requiredEnvNames),
    ...results.flatMap((result) => result.missingEnv || [])
  ]);
  const warnings = allChecks
    .filter((check) => check.status === 'warn')
    .map(warningSummary);
  const missingCustomDimensions = unique(results.flatMap((result) => result.missingCustomDimensions || []));
  const missingKeyEvents = unique(results.flatMap((result) => result.missingKeyEvents || []));
  const missingDlvs = unique(results.flatMap((result) => result.missingDlvs || []));
  const missingTriggers = unique(results.flatMap((result) => result.missingTriggers || []));
  const ga4Result = results.find((result) => result.name === 'GA4 checks');
  const gtmResult = results.find((result) => result.name === 'GTM checks');
  const ga4Evaluated = Boolean(ga4Result && ga4Result.liveApiChecked);
  const gtmEvaluated = Boolean(gtmResult && gtmResult.liveApiChecked);
  const permissionIssues = allChecks
    .filter((check) => /permission|PERMISSION_DENIED|unauthorized|forbidden|HTTP 401|HTTP 403/i.test(`${check.label} ${check.details || ''}`))
    .map((check) => `${check.label}: ${check.details}`);

  const lines = [
    '# CRBOX Marketing Ops Readiness Report',
    '',
    `Generated: ${timestamp}`,
    '',
    `Mode: **${EXPECTED.mode}**`,
    '',
    '> This report is generated by a read-only repository checker scaffold. No GA4, GTM, Google Ads, or Meta platform mutations were performed.',
    '',
    '## Summary',
    '',
    `- Passed checks: ${summary.pass || 0}`,
    `- Warnings: ${summary.warn || 0}`,
    `- Skipped checks: ${summary.skipped || 0}`,
    `- Missing environment variables: ${missingEnvNames.length}`,
    '',
    '## Missing Environment Variables',
    '',
    missingEnvNames.length ? missingEnvNames.map((name) => `- \`${name}\``).join('\n') : '- None detected for the checks that ran.',
    '',
    '## Warnings',
    '',
    warnings.length ? warnings.map((warning) => `- ${warning}`).join('\n') : '- None.',
    '',
    '## Live Platform Gaps',
    '',
    'Missing GA4 custom dimensions:',
    ga4Evaluated
      ? (missingCustomDimensions.length ? missingCustomDimensions.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GA4 live API check did not complete.',
    '',
    'Missing GA4 key events/conversions:',
    ga4Evaluated
      ? (missingKeyEvents.length ? missingKeyEvents.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GA4 live API check did not complete.',
    '',
    'Missing GTM Data Layer Variables:',
    gtmEvaluated
      ? (missingDlvs.length ? missingDlvs.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GTM live API check did not complete.',
    '',
    'Missing GTM triggers:',
    gtmEvaluated
      ? (missingTriggers.length ? missingTriggers.map((item) => `- \`${item}\``).join('\n') : '- None detected.')
      : '- Not evaluated; GTM live API check did not complete.',
    '',
    'Permission or scope issues:',
    permissionIssues.length ? permissionIssues.map((item) => `- ${item}`).join('\n') : '- None detected.',
    '',
    '## Dry-Run Plan Summary',
    '',
    plan
      ? `- Generated: ${plan.generatedAt}
- Mode: ${plan.mode}
- Proposed GA4 actions: ${plan.summary ? plan.summary.totalProposedGa4Actions : 0}
- Proposed GTM actions: ${plan.summary ? plan.summary.totalProposedGtmActions : 0}
- Blocked actions: ${plan.summary ? plan.summary.totalBlockedActions : 0}
- Risk summary: ${plan.summary ? JSON.stringify(plan.summary.riskSummary) : '{}'}
- Mutation performed: ${plan.mutationPerformed}
- Plan files: \`docs/marketing-ops-dry-run-plan.md\`, \`docs/marketing-ops-dry-run-plan.json\``
      : '- No dry-run plan file found yet.',
    '',
    '## Controlled Apply Readiness',
    '',
    apply
      ? `- Dry-run plan valid: ${apply.dryRunPlanValid}
- Controlled apply execution enabled: ${apply.controlledApplyExecutionEnabled}
- Eligible GA4 actions: ${apply.eligibleGa4Actions}
- Eligible GTM actions: ${apply.eligibleGtmActions}
- Blocked actions: ${apply.blockedActions}
- Future execution previews: ${apply.futureExecutionPreviews ? apply.futureExecutionPreviews.length : 0}
- Validation errors: ${apply.validationErrors ? apply.validationErrors.length : 0}`
      : '- Not evaluated in this run.',
    '',
    'No controlled apply mutations were performed. Phase 2C-Prep validates apply readiness only.',
    '',
    '## Phase 2D GA4 Controlled Create',
    '',
    `- GA4 controlled create capability implemented: true
- GA4 controlled create execution currently run: ${ga4CreateResult.exists && ga4CreateResult.status !== 'not_executed'}
- GA4 write execution requires explicit env + flags: true
- GTM controlled create enabled: false
- Google Ads enabled: false
- Meta enabled: false
- Last GA4 create result file exists: ${ga4CreateResult.exists}
- Last GA4 create result status: ${ga4CreateResult.status || 'not_executed'}`,
    '',
    'No Phase 2D GA4 controlled-create mutations are performed unless the dedicated GA4 create command passes every required safety gate.',
    '',
    '## Phase 2F GTM Controlled Create Prep',
    '',
    `- GTM controlled create capability implemented: true
- GTM controlled create execution currently run: ${gtmCreateResult.exists && gtmCreateResult.status !== 'not_executed'}
- GTM write execution requires explicit env + flags: true
- GTM publish enabled: false
- Google Ads enabled: false
- Meta enabled: false
- Last GTM create result file exists: ${gtmCreateResult.exists}
- Last GTM create result status: ${gtmCreateResult.status || 'not_executed'}
- Last GTM create result mutationPerformed: ${Boolean(gtmCreateResult.mutationPerformed)}`,
    '',
    'No GTM container versions are created and GTM publishing remains a separate blocked phase requiring explicit approval.',
    '',
    '## Phase 2G GTM Pre-flight',
    '',
    gtmPreflight
      ? `- Generated: ${gtmPreflight.generatedAt}
- Mode: ${gtmPreflight.mode}
- Plan valid: ${gtmPreflight.planValidation.ok}
- Workspace readable: ${gtmPreflight.workspace.workspaceReadable}
- Variables readable: ${gtmPreflight.workspace.variablesReadable}
- Triggers readable: ${gtmPreflight.workspace.triggersReadable}
- Required GTM edit scope status: ${gtmPreflight.oauth.requiredScopeStatus}
- Future actions checked: ${gtmPreflight.futureActions.total}
- Already existing: ${gtmPreflight.futureActions.alreadyExists}
- Would create later: ${gtmPreflight.futureActions.wouldCreate}
- Duplicate risk: ${gtmPreflight.futureActions.duplicateRisk}
- Blocked unsafe proposed actions: ${gtmPreflight.futureActions.blocked}
- Ready for future human review: ${gtmPreflight.recommendation.readyForFutureControlledCreate}`
      : '- No GTM pre-flight artifact found yet.',
    '',
    'No GTM write calls were made by the Phase 2G pre-flight. No variables, triggers, tags, versions, or publishes were created.',
    '',
    ...results.map(sectionForResult),
    '## Recommended Next Actions',
    '',
    '- Keep this agent in `read_only` mode.',
    '- Add credentials only through environment variables; never commit secrets.',
    '- Use GA4/GTM live checks only to verify state; do not create GTM workspaces, tags, GA4 dimensions, Google Ads conversions, or Meta assets from this version.',
    '',
    '## Mutation Statement',
    '',
    'No platform mutations were performed. This run did not create, update, publish, delete, or mutate GA4, GTM, Google Ads, or Meta objects.'
  ];

  return lines.join('\n') + '\n';
}

function writeMarkdownReport(root, results, options = {}) {
  const outputPath = path.join(root, 'docs', 'marketing-ops-readiness-report.md');
  const apply = options.apply || (() => {
    const validation = validateDryRunPlan(root);
    return {
      dryRunPlanValid: validation.ok,
      controlledApplyExecutionEnabled: false,
      eligibleGa4Actions: validation.ok ? validation.ga4Actions.length : 0,
      eligibleGtmActions: validation.ok ? validation.gtmActions.length : 0,
      blockedActions: validation.blockedActions.length,
      futureExecutionPreviews: [],
      validationErrors: validation.errors || []
    };
  })();
  const markdown = buildMarkdownReport(results, {
    ...options,
    plan: options.plan || readDryRunPlan(root),
    apply,
    root
  });
  fs.writeFileSync(outputPath, markdown, 'utf8');
  return outputPath;
}

module.exports = {
  buildMarkdownReport,
  writeMarkdownReport
};
