'use strict';

const fs = require('fs');
const path = require('path');
const { EXPECTED, REQUIRED_ENV } = require('../config');
const { missingEnv, summarizeStatus, unique } = require('../utils');

function sectionForResult(result) {
  const lines = [
    `## ${result.name}`,
    '',
    `Status: **${String(result.status || 'info').toUpperCase()}**`,
    ''
  ];

  if (result.notes && result.notes.length) {
    lines.push('Notes:');
    for (const note of result.notes) {
      lines.push(`- ${note}`);
    }
    lines.push('');
  }

  if (result.inspectedFiles && result.inspectedFiles.length) {
    lines.push('Inspected files:');
    for (const file of result.inspectedFiles) {
      lines.push(`- \`${file}\``);
    }
    lines.push('');
  }

  lines.push('| Check | Status | Details |');
  lines.push('|---|---:|---|');
  for (const check of result.checks || []) {
    const details = check.details || '';
    lines.push(`| ${check.label} | ${String(check.status).toUpperCase()} | ${details.replace(/\|/g, '\\|')} |`);
  }
  lines.push('');

  if (result.futureChecks && result.futureChecks.length) {
    lines.push('Future read-only API checks planned for this module:');
    for (const item of result.futureChecks) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildMarkdownReport(results, options = {}) {
  const timestamp = options.timestamp || new Date().toISOString();
  const allChecks = results.flatMap((result) => result.checks || []);
  const summary = summarizeStatus(allChecks);
  const requiredEnvNames = unique(Object.values(REQUIRED_ENV).flat());
  const missingEnvNames = unique([
    ...missingEnv(requiredEnvNames),
    ...results.flatMap((result) => result.missingEnv || [])
  ]);
  const warnings = allChecks
    .filter((check) => check.status === 'warn')
    .map((check) => check.label);

  const lines = [
    '# CRBOX Marketing Ops Readiness Report',
    '',
    `Generated: ${timestamp}`,
    '',
    `Mode: **${EXPECTED.mode}**`,
    '',
    '> This report is generated by a read-only repository checker scaffold. No GA4, GTM, Google Ads, or Meta platform mutations were performed.',
    '',
    '## Summary',
    '',
    `- Passed checks: ${summary.pass || 0}`,
    `- Warnings: ${summary.warn || 0}`,
    `- Skipped checks: ${summary.skipped || 0}`,
    `- Missing environment variables: ${missingEnvNames.length}`,
    '',
    '## Missing Environment Variables',
    '',
    missingEnvNames.length ? missingEnvNames.map((name) => `- \`${name}\``).join('\n') : '- None detected for the checks that ran.',
    '',
    '## Warnings',
    '',
    warnings.length ? warnings.map((warning) => `- ${warning}`).join('\n') : '- None.',
    '',
    ...results.map(sectionForResult),
    '## Recommended Next Actions',
    '',
    '- Keep this agent in `read_only` mode until platform read-only API checks are implemented and reviewed.',
    '- Add credentials only through environment variables; never commit secrets.',
    '- In a later task, add read-only API clients for GA4 Admin, GTM, Google Ads, and Meta Marketing APIs.',
    '- Use live platform checks only to verify state; do not create GTM workspaces, tags, GA4 dimensions, Google Ads conversions, or Meta assets from this first version.',
    '',
    '## Mutation Statement',
    '',
    'No platform mutations were performed. This run did not create, update, publish, delete, or mutate GA4, GTM, Google Ads, or Meta objects.'
  ];

  return lines.join('\n') + '\n';
}

function writeMarkdownReport(root, results) {
  const outputPath = path.join(root, 'docs', 'marketing-ops-readiness-report.md');
  const markdown = buildMarkdownReport(results);
  fs.writeFileSync(outputPath, markdown, 'utf8');
  return outputPath;
}

module.exports = {
  buildMarkdownReport,
  writeMarkdownReport
};
