// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crbox-chat/Concierge.tsx": () => import("../components/mockups/crbox-chat/Concierge.tsx"),
  "./components/mockups/crbox-chat/Editorial.tsx": () => import("../components/mockups/crbox-chat/Editorial.tsx")
};
