#!/usr/bin/env python3
"""
Task #384 — Product Brain Expansion Batch 2 (~260 more rows → total ~700+).
Fills sparse categories and broadens high-interest areas.
"""
import json, sys

def q(s): return "'" + s.replace("'", "\\'") + "'"
def js_list(items): return '[' + ','.join(q(i) for i in items) + ']'

def row_to_js(r):
    parts = [
        f"productKey:{q(r['productKey'])}",
        f"productName:{q(r['productName'])}",
        f"categoryId:{q(r['categoryId'])}",
        f"aliases:{js_list(r.get('aliases',[]))}",
        f"misspellings:{js_list(r.get('misspellings',[]))}",
        f"englishTerms:{js_list(r.get('englishTerms',[]))}",
        f"spanishTerms:{js_list(r.get('spanishTerms',[]))}",
        f"ecommerceTerms:{js_list(r.get('ecommerceTerms',[]))}",
        f"commonSearchPhrases:{js_list(r.get('commonSearchPhrases',[]))}",
        f"riskOverrideFlags:{js_list(r.get('riskOverrideFlags',[]))}",
        f"customerHint:{q(r.get('customerHint',''))}",
        f"adminHint:{q(r.get('adminHint',''))}",
    ]
    return '    { ' + ', '.join(parts) + ' },'

BATCH2 = [

  # ══ MICROPHONES & AUDIO PRO ═══════════════════════════════════════════════
  { 'productKey':'microfono_usb', 'productName':'Micrófono USB / Blue Yeti / Podcast', 'categoryId':'microphones_audio_pro',
    'aliases':['micrófono usb','blue yeti','podcast mic','rode nt-usb','shure mv7'],
    'misspellings':['microfono usb','micro usb'],
    'englishTerms':['usb microphone','blue yeti','shure mv7'],
    'spanishTerms':['micrófono usb','micrófono podcast'],
    'ecommerceTerms':['Blue Yeti USB Microphone','Shure MV7 Podcast Mic','Rode NT-USB Mini'],
    'commonSearchPhrases':['micrófono usb precio','blue yeti comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'microfono_condensador', 'productName':'Micrófono de Condensador / XLR / Audio Interface', 'categoryId':'microphones_audio_pro',
    'aliases':['micrófono condensador','xlr mic','audio interface','focusrite scarlett'],
    'misspellings':['microfono condensador','focusrite scarlet'],
    'englishTerms':['condenser microphone','focusrite scarlett solo','audio interface'],
    'spanishTerms':['micrófono de condensador','interfaz de audio'],
    'ecommerceTerms':['Audio-Technica AT2020','Focusrite Scarlett Solo 4th Gen','Rode NT1 5th Gen'],
    'commonSearchPhrases':['micrófono condensador precio','focusrite scarlett comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'interfaz_audio', 'productName':'Interfaz de Audio / Focusrite / PreSonus', 'categoryId':'microphones_audio_pro',
    'aliases':['interfaz audio','audio interface','focusrite','presonus audiobox','universal audio'],
    'misspellings':['interfaz de audio focusrite'],
    'englishTerms':['audio interface','focusrite scarlett 2i2','presonus audiobox'],
    'spanishTerms':['interfaz de audio','tarjeta de sonido externa'],
    'ecommerceTerms':['Focusrite Scarlett 2i2 4th Gen','PreSonus AudioBox USB 96'],
    'commonSearchPhrases':['interfaz audio precio','focusrite 2i2 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'controlador_dj', 'productName':'Controlador DJ / Pioneer / Native Instruments', 'categoryId':'microphones_audio_pro',
    'aliases':['controlador dj','pioneer dj','ddj-400','native instruments','traktor'],
    'misspellings':['controlador de dj'],
    'englishTerms':['dj controller','pioneer ddj-400','native instruments traktor kontrol'],
    'spanishTerms':['controlador dj','mixer dj'],
    'ecommerceTerms':['Pioneer DJ DDJ-400','Native Instruments Traktor Kontrol S4 MK3'],
    'commonSearchPhrases':['controlador dj precio','pioneer ddj-400 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ EYEWEAR / OPTICAL ════════════════════════════════════════════════════
  { 'productKey':'lentes_contacto', 'productName':'Lentes de Contacto / Acuvue / Alcon', 'categoryId':'eyewear_medical_contact_lenses',
    'aliases':['lentes de contacto','contact lenses','acuvue oasys','alcon air optix'],
    'misspellings':['lentes contacto'],
    'englishTerms':['contact lenses','acuvue oasys','daily contacts'],
    'spanishTerms':['lentes de contacto','pupilentes'],
    'ecommerceTerms':['Acuvue Oasys 1-Day','Alcon Dailies AquaComfort Plus'],
    'commonSearchPhrases':['lentes de contacto precio','acuvue comprar'],
    'riskOverrideFlags':['medical','sanitary_review'],
    'customerHint':'Los lentes de contacto son dispositivos médicos y pueden requerir revisión sanitaria.',
    'adminHint':'Verificar si requiere prescripción y registro sanitario.' },

  { 'productKey':'lentes_lectura', 'productName':'Lentes de Lectura / Blue Light Glasses', 'categoryId':'eyewear_optical',
    'aliases':['lentes de lectura','blue light glasses','antireflejos','gafas luz azul'],
    'misspellings':['lentes de leer'],
    'englishTerms':['reading glasses','blue light blocking glasses'],
    'spanishTerms':['gafas para leer','lentes para computadora'],
    'ecommerceTerms':["Foster Grant Reading Glasses","Felix Gray Blue Light Glasses"],
    'commonSearchPhrases':['lentes de lectura precio','blue light glasses comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ PET FOOD & ACCESSORIES ════════════════════════════════════════════════
  { 'productKey':'comida_perro_premium', 'productName':'Comida Premium Perro / Royal Canin / Orijen', 'categoryId':'pet_food_supplements_review',
    'aliases':['comida perro premium','royal canin','orijen','blue buffalo','dog food premium'],
    'misspellings':['royal canin perro'],
    'englishTerms':['premium dog food','royal canin','orijen original'],
    'spanishTerms':['comida premium para perro','alimento premium canino'],
    'ecommerceTerms':["Royal Canin Medium Adult Dry Dog Food","Orijen Original Dry Dog Food"],
    'commonSearchPhrases':['comida premium perro precio','royal canin comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos importados para mascotas pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA para alimentos de mascotas.' },

  { 'productKey':'comida_gato_premium', 'productName':'Comida Premium Gato / Purina Pro Plan / Hills', 'categoryId':'pet_food_supplements_review',
    'aliases':['comida gato premium','purina pro plan','hills science diet','wet cat food'],
    'misspellings':['purina pro plan gato'],
    'englishTerms':["hill's science diet cat","purina pro plan cat"],
    'spanishTerms':['comida premium para gato','alimento premium felino'],
    'ecommerceTerms':["Hill's Science Diet Adult Cat Food","Purina Pro Plan Wet Cat Food"],
    'commonSearchPhrases':['comida premium gato precio','hills gato comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos importados para mascotas pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA.' },

  { 'productKey':'suplemento_mascota', 'productName':'Suplemento Mascota / Articulaciones / Omega', 'categoryId':'pet_food_supplements_review',
    'aliases':['suplemento mascotas','omega para perro','glucosamina perro','pet supplement'],
    'misspellings':['suplemento para mascotas'],
    'englishTerms':['dog joint supplement','omega 3 for dogs','pet vitamins'],
    'spanishTerms':['suplemento para mascotas','omega para perros'],
    'ecommerceTerms':['Zesty Paws Mobility Bites','Nutramax Dasuquin with MSM'],
    'commonSearchPhrases':['suplemento mascota precio'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos para mascotas pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA.' },

  { 'productKey':'juguete_mascota', 'productName':'Juguete Mascota / Kong / Chew Toy', 'categoryId':'pet_accessories',
    'aliases':['juguete perro','kong dog','chew toy','ball launcher','fetch toy'],
    'misspellings':['juguete de perro'],
    'englishTerms':['dog toy','kong dog toy','chew toy'],
    'spanishTerms':['juguete para perro','juguete para gato'],
    'ecommerceTerms':['KONG Classic Dog Toy','Chuckit! Ultra Ball','ZippyPaws Skinny Peltz'],
    'commonSearchPhrases':['juguete perro precio','kong dog comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'comedero_automatico', 'productName':'Comedero Automático / Pet Feeder / Fountain', 'categoryId':'pet_accessories',
    'aliases':['comedero automático','pet feeder','fuente agua gato','automatic feeder'],
    'misspellings':['comedero automatico mascota'],
    'englishTerms':['automatic pet feeder','pet water fountain'],
    'spanishTerms':['comedero automático','bebedero fuente para gato'],
    'ecommerceTerms':['PetSafe Automatic Pet Feeder','Catit Flower Fountain'],
    'commonSearchPhrases':['comedero automático precio','pet feeder comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ PLANTS / AGRO ═════════════════════════════════════════════════════════
  { 'productKey':'planta_artificial', 'productName':'Planta Artificial / Decoración / Succulents', 'categoryId':'home_decor_storage',
    'aliases':['plantas artificiales','planta decorativa','succulents artificiales','faux plant'],
    'misspellings':['plantas artificiales decoracion'],
    'englishTerms':['artificial plant','faux succulent','fake plant decor'],
    'spanishTerms':['plantas artificiales','plantas decorativas'],
    'ecommerceTerms':['Nearly Natural 5-ft Fiddle Leaf','IKEA FEJKA Artificial Plant'],
    'commonSearchPhrases':['planta artificial precio','plantas decorativas comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'tierra_sustrato', 'productName':'Tierra / Sustrato Especial / Musgo', 'categoryId':'plants_seeds_agro_review',
    'aliases':['sustrato especial','musgo sphagnum','tierra para orquídeas','perlita'],
    'misspellings':['sustrato para plantas'],
    'englishTerms':['sphagnum moss','orchid potting mix','perlite'],
    'spanishTerms':['sustrato para plantas','tierra especial'],
    'ecommerceTerms':["Miracle-Gro Orchid Potting Mix","Hoffman Horticultural Perlite"],
    'commonSearchPhrases':['sustrato especial precio','musgo sphagnum comprar'],
    'riskOverrideFlags':['agro','phytosanitary_review'],
    'customerHint':'Los sustratos y materiales de origen vegetal pueden requerir revisión fitosanitaria.',
    'adminHint':'Validar SFE/SENASA.' },

  # ══ CLOTHING ACCESSORIES ══════════════════════════════════════════════════
  { 'productKey':'gorra_snapback', 'productName':'Gorra / Snapback / Cap / Beanie', 'categoryId':'clothing_accessories',
    'aliases':['gorra snapback','snapback','beanie','gorra nueva era','hat cap'],
    'misspellings':['gorra snap back'],
    'englishTerms':['snapback cap','fitted hat','beanie hat','new era cap'],
    'spanishTerms':['gorra','cachucha','gorro beanie'],
    'ecommerceTerms':['New Era 59FIFTY Fitted Cap','Carhartt Acrylic Watch Hat'],
    'commonSearchPhrases':['gorra snapback precio','new era cap comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cinturon_cuero', 'productName':'Cinturón / Belt / Piel / Coach', 'categoryId':'clothing_accessories',
    'aliases':['cinturón cuero','belt leather','cinturón de cuero','correa'],
    'misspellings':['cinturon cuero'],
    'englishTerms':['leather belt','dress belt'],
    'spanishTerms':['cinturón de cuero','correa'],
    'ecommerceTerms':["Levi's Men's Reversible Casual Jeans Belt","Coach Men's Harness Buckle Cut-To-Size Belt"],
    'commonSearchPhrases':['cinturón precio','belt cuero comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'bufanda_lana', 'productName':'Bufanda / Scarf / Lana / Cachmere', 'categoryId':'clothing_accessories',
    'aliases':['bufanda lana','scarf','bufanda cashmere','pañoleta'],
    'misspellings':['bufanda de lana'],
    'englishTerms':['wool scarf','cashmere scarf'],
    'spanishTerms':['bufanda','pañoleta'],
    'ecommerceTerms':['Acne Studios Scarf','Uniqlo Heattech Inner Scarf'],
    'commonSearchPhrases':['bufanda precio','scarf cashmere comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'guantes_invierno', 'productName':'Guantes de Invierno / Touchscreen Gloves', 'categoryId':'clothing_accessories',
    'aliases':['guantes invierno','touchscreen gloves','guantes táctiles'],
    'misspellings':['guantes de invierno'],
    'englishTerms':['winter gloves','touchscreen gloves'],
    'spanishTerms':['guantes de invierno','guantes de pantalla táctil'],
    'ecommerceTerms':["Mujjo Full Leather Touchscreen Gloves","The North Face Etip Gloves"],
    'commonSearchPhrases':['guantes invierno precio','touchscreen gloves comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ ELECTRONICS — MORE ACCESSORIES ═══════════════════════════════════════
  { 'productKey':'funda_iphone', 'productName':'Funda iPhone / Case / MagSafe Compatible', 'categoryId':'phones_smartphones',
    'aliases':['funda iphone','case iphone','magsafe case','phone case','carcasa iphone'],
    'misspellings':['funda de iphone'],
    'englishTerms':['iphone case','magsafe compatible case','clear case iphone'],
    'spanishTerms':['funda para iphone','carcasa iphone'],
    'ecommerceTerms':['Apple Clear Case with MagSafe','Casetify Impact Case','OtterBox Defender'],
    'commonSearchPhrases':['funda iphone 15 precio','case magsafe comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'protector_pantalla', 'productName':'Protector de Pantalla / Vidrio Templado', 'categoryId':'phones_smartphones',
    'aliases':['protector pantalla','vidrio templado','screen protector','tempered glass'],
    'misspellings':['protector de pantalla'],
    'englishTerms':['tempered glass screen protector','screen protector'],
    'spanishTerms':['protector de pantalla','vidrio templado'],
    'ecommerceTerms':['amFilm 2-Pack Tempered Glass','Belkin UltraGlass Screen Protector'],
    'commonSearchPhrases':['protector pantalla precio','vidrio templado comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'soporte_celular_auto', 'productName':'Soporte Celular / Car Mount / Magnético', 'categoryId':'automotive_simple_accessories',
    'aliases':['soporte celular auto','car mount','soporte magnético carro','phone holder car'],
    'misspellings':['soporte para celular en carro'],
    'englishTerms':['car phone mount','magnetic phone holder'],
    'spanishTerms':['soporte para celular en carro','sostenedor celular'],
    'ecommerceTerms':['Anker Car Phone Mount','iOttie Easy One Touch 5'],
    'commonSearchPhrases':['soporte celular carro precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'lente_telefono', 'productName':'Lente para Teléfono / Clip Lens / Wide Angle', 'categoryId':'cameras_photo_video',
    'aliases':['lente teléfono','clip lens','wide angle phone','macro lens phone'],
    'misspellings':['lente de celular'],
    'englishTerms':['clip-on phone lens','wide angle smartphone lens'],
    'spanishTerms':['lente para teléfono','lente gran angular celular'],
    'ecommerceTerms':['Moment Wide Lens 18mm','Moment Macro Lens 10x'],
    'commonSearchPhrases':['lente para teléfono precio','clip lens comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'tripode_fotografia', 'productName':'Trípode Fotográfico / Gorilla Pod / Travel', 'categoryId':'cameras_photo_video',
    'aliases':['trípode','gorilla pod','tripod','tripié cámara'],
    'misspellings':['tripode fotografia','tripie'],
    'englishTerms':['camera tripod','gorilla pod','travel tripod'],
    'spanishTerms':['trípode','tripié cámara'],
    'ecommerceTerms':['GorillaPod 3K Pro','Peak Design Travel Tripod','Joby GripTight Pro'],
    'commonSearchPhrases':['trípode precio','gorilla pod comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'microfono_lavalier', 'productName':'Micrófono Lavalier / DJI Mic / Rode', 'categoryId':'microphones_audio_pro',
    'aliases':['micrófono lavalier','lav mic','dji mic','rode wireless go','clip mic'],
    'misspellings':['microfono lavalier'],
    'englishTerms':['lavalier microphone','dji mic mini','rode wireless go 2'],
    'spanishTerms':['micrófono de solapa','lav mic'],
    'ecommerceTerms':['DJI Mic Mini','Rode Wireless GO II','Movo LV4-O'],
    'commonSearchPhrases':['micrófono lavalier precio','dji mic comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'gimbal_celular', 'productName':'Gimbal para Celular / DJI OM / Hohem', 'categoryId':'cameras_photo_video',
    'aliases':['gimbal celular','dji om 6','estabilizador celular','phone stabilizer'],
    'misspellings':['gimbal de celular'],
    'englishTerms':['phone gimbal','dji om 6','hohem isteady'],
    'spanishTerms':['gimbal para celular','estabilizador de teléfono'],
    'ecommerceTerms':['DJI OM 6 Smartphone Gimbal','Hohem iSteady M6'],
    'commonSearchPhrases':['gimbal celular precio','dji om 6 comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'ring_light', 'productName':'Ring Light / Aro de Luz / Streaming Light', 'categoryId':'cameras_photo_video',
    'aliases':['ring light','aro de luz','led ring light','streaming light'],
    'misspellings':['ring lite'],
    'englishTerms':['ring light','led ring light'],
    'spanishTerms':['aro de luz','ring light'],
    'ecommerceTerms':['Neewer 18-inch Ring Light Kit','Elgato Key Light'],
    'commonSearchPhrases':['ring light precio','aro de luz comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'teclado_bluetooth_tablet', 'productName':'Teclado Bluetooth / Logitech Keys-To-Go', 'categoryId':'computer_accessories',
    'aliases':['teclado bluetooth','logitech keys to go','teclado inalámbrico tablet'],
    'misspellings':['teclado bluetooh'],
    'englishTerms':['bluetooth keyboard','logitech keys-to-go','folding keyboard'],
    'spanishTerms':['teclado inalámbrico','teclado bluetooth'],
    'ecommerceTerms':['Logitech Keys-To-Go 2','Logitech MX Keys Mini','Microsoft Designer Compact Keyboard'],
    'commonSearchPhrases':['teclado bluetooth precio','logitech mx keys comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'ups_regulador', 'productName':'UPS / Regulador de Voltaje / APC', 'categoryId':'computer_accessories',
    'aliases':['ups','regulador voltaje','apc ups','no break','back-ups'],
    'misspellings':['regulador de voltaje'],
    'englishTerms':['ups battery backup','voltage regulator','apc back-ups'],
    'spanishTerms':['ups','regulador de voltaje','no-break'],
    'ecommerceTerms':['APC Back-UPS 600VA','CyberPower CP1500PFCLCD'],
    'commonSearchPhrases':['ups precio','regulador voltaje comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'extension_electrica', 'productName':'Extensión Eléctrica / Power Strip / Surge Protector', 'categoryId':'computer_accessories',
    'aliases':['extensión eléctrica','power strip','regleta','surge protector','extensión con USB'],
    'misspellings':['extension electrica'],
    'englishTerms':['power strip','surge protector','extension cord with usb'],
    'spanishTerms':['extensión eléctrica','regleta con USB'],
    'ecommerceTerms':['Anker PowerStrip 6-Outlet','Tripp Lite 8-Outlet Surge Protector'],
    'commonSearchPhrases':['extensión eléctrica precio','power strip comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'camara_seguridad_ip', 'productName':'Cámara de Seguridad IP / WiFi / TP-Link Tapo', 'categoryId':'networking_equipment',
    'aliases':['cámara seguridad ip','cámara wifi','tapo camera','wyze cam','reolink'],
    'misspellings':['camara de seguridad ip'],
    'englishTerms':['ip security camera','wifi camera','tp-link tapo'],
    'spanishTerms':['cámara de seguridad wifi','cámara ip'],
    'ecommerceTerms':['TP-Link Tapo C310','Reolink E1 Outdoor','Wyze Cam v3'],
    'commonSearchPhrases':['cámara seguridad wifi precio','tapo camera comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'nas_storage', 'productName':'NAS / Network Storage / Synology', 'categoryId':'storage_memory',
    'aliases':['nas synology','qnap','network attached storage','servidor nas'],
    'misspellings':['nas storage'],
    'englishTerms':['nas server','synology ds223','qnap ts-233'],
    'spanishTerms':['almacenamiento en red','nas'],
    'ecommerceTerms':['Synology DiskStation DS223','QNAP TS-233'],
    'commonSearchPhrases':['nas precio','synology comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE CLOTHING ══════════════════════════════════════════════════════════
  { 'productKey':'ropa_outdoor_gore', 'productName':'Chaqueta Outdoor / Gore-Tex / North Face', 'categoryId':'sports_outdoor_variable',
    'aliases':['chaqueta gore-tex','north face jacket','patagonia','chaqueta outdoor'],
    'misspellings':['chaqueta gore tex'],
    'englishTerms':['gore-tex jacket','waterproof jacket','north face resolve'],
    'spanishTerms':['chaqueta impermeable','cortaviento'],
    'ecommerceTerms':["The North Face Resolve 2 Jacket","Patagonia Torrentshell 3L"],
    'commonSearchPhrases':['chaqueta gore-tex precio','north face comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'camisa_hawaiana', 'productName':'Camisa Hawaiana / Resort Wear / Tropical', 'categoryId':'clothing_general',
    'aliases':['camisa hawaiana','hawaiian shirt','camisa tropical','aloha shirt'],
    'misspellings':['camisa hawaiiana'],
    'englishTerms':['hawaiian shirt','aloha shirt','resort shirt'],
    'spanishTerms':['camisa hawaiana','camisa floral'],
    'ecommerceTerms':["Reyn Spooner Classic Fit Hawaiian Shirt","Tommy Bahama Camp Shirt"],
    'commonSearchPhrases':['camisa hawaiana precio','aloha shirt comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'ropa_termica', 'productName':'Ropa Térmica / Base Layer / Smartwool', 'categoryId':'clothing_general',
    'aliases':['ropa térmica','base layer','smartwool','merino wool base','thermal underwear'],
    'misspellings':['ropa termica'],
    'englishTerms':['thermal base layer','merino wool shirt','smartwool base layer'],
    'spanishTerms':['ropa interior térmica','base layer'],
    'ecommerceTerms':['Smartwool Merino 150 Base Layer','Icebreaker 200 Oasis Crew'],
    'commonSearchPhrases':['ropa térmica precio','base layer merino comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'pantalon_cargo', 'productName':'Pantalón Cargo / Tactical / Multi-bolsillo', 'categoryId':'clothing_general',
    'aliases':['pantalón cargo','cargo pants','pantalón táctico','pantalón multi bolsillo'],
    'misspellings':['pantalon cargo'],
    'englishTerms':['cargo pants','tactical pants'],
    'spanishTerms':['pantalón cargo','pantalón con muchos bolsillos'],
    'ecommerceTerms':["Carhartt Men's Rugged Flex Rigby Cargo Pant","5.11 Tactical Stryke Pant"],
    'commonSearchPhrases':['pantalón cargo precio','cargo pants comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'traje_bano', 'productName':'Traje de Baño / Bikini / Bañador', 'categoryId':'clothing_general',
    'aliases':['traje de baño','bikini','bañador','swimsuit','traje baño mujer'],
    'misspellings':['traje de baño'],
    'englishTerms':['swimsuit','bikini','swim trunks'],
    'spanishTerms':['traje de baño','bañador'],
    'ecommerceTerms':['Cupshe One-Piece Swimsuit','Speedo Endurance+ Swimsuit','O\'Neill Board Shorts'],
    'commonSearchPhrases':['traje de baño precio','bikini comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'medias_socks_pack', 'productName':'Medias / Calcetines Pack / Bombas Socks', 'categoryId':'clothing_general',
    'aliases':['medias pack','calcetines bombas','bombas socks','lululemon socks'],
    'misspellings':['calcetines pack'],
    'englishTerms':['socks multipack','bombas ankle socks'],
    'spanishTerms':['medias pack','calcetines'],
    'ecommerceTerms':['Bombas Ankle Socks 4-Pack','Lululemon Power Stride Ankle Socks'],
    'commonSearchPhrases':['calcetines pack precio','bombas socks comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE BEAUTY ═══════════════════════════════════════════════════════════
  { 'productKey':'aceite_rosehip', 'productName':'Aceite Facial / Rosehip / Argan / Bakuchiol', 'categoryId':'beauty_skincare_personal_care',
    'aliases':['aceite rosehip','aceite facial','argan oil','bakuchiol oil','rosehip oil'],
    'misspellings':['aceite de rosa mosqueta'],
    'englishTerms':['rosehip seed oil','argan oil','facial oil'],
    'spanishTerms':['aceite de rosa mosqueta','aceite facial'],
    'ecommerceTerms':["Trilogy Certified Pure Rosehip Oil","Josie Maran 100% Pure Argan Oil"],
    'commonSearchPhrases':['aceite rosehip precio','argan oil comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'exfoliante_corporal', 'productName':'Exfoliante Corporal / Scrub / AHA BHA', 'categoryId':'beauty_skincare_personal_care',
    'aliases':['exfoliante corporal','body scrub','aha bha exfoliant','scrub azucar'],
    'misspellings':['exfoliante corporal'],
    'englishTerms':['body scrub','aha exfoliant','bha toner'],
    'spanishTerms':['exfoliante corporal','scrub de azúcar'],
    'ecommerceTerms':["Tree Hut Shea Sugar Scrub","Paula's Choice BHA Exfoliant"],
    'commonSearchPhrases':['exfoliante corporal precio','body scrub comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'crema_manos_lujo', 'productName':'Crema de Manos Lujo / L\'Occitane / Aesop', 'categoryId':'beauty_skincare_personal_care',
    'aliases':["crema manos l'occitane","aesop hand cream","crema de manos lujo"],
    'misspellings':['crema de manos'],
    'englishTerms':["l'occitane hand cream","aesop resurrection aromatique hand balm"],
    'spanishTerms':['crema de manos de lujo'],
    'ecommerceTerms':["L'Occitane Shea Butter Hand Cream 150ml","Aesop Resurrection Hand Balm"],
    'commonSearchPhrases':["crema manos l'occitane precio"],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'shampoo_seco', 'productName':'Shampoo Seco / Dry Shampoo / Batiste', 'categoryId':'beauty_skincare_personal_care',
    'aliases':['shampoo seco','dry shampoo','batiste','not your mothers dry shampoo'],
    'misspellings':['shampoo en seco'],
    'englishTerms':['dry shampoo','batiste dry shampoo'],
    'spanishTerms':['shampoo seco','champú en seco'],
    'ecommerceTerms':["Batiste Dry Shampoo Original","Living Proof Perfect Hair Day Dry Shampoo"],
    'commonSearchPhrases':['shampoo seco precio','dry shampoo comprar'],
    'riskOverrideFlags':['aerosol'], 'customerHint':'Aerosol — puede tener restricciones de transporte.', 'adminHint':'Revisar normativa aerosoles.' },

  { 'productKey':'kit_unas', 'productName':'Kit Uñas / Nail Art / Gel UV / Polygel', 'categoryId':'beauty_makeup_cosmetics',
    'aliases':['kit uñas gel','polygel kit','nail art','lampara uñas uv'],
    'misspellings':['kit de uñas'],
    'englishTerms':['nail art kit','polygel nail kit','uv led nail lamp'],
    'spanishTerms':['kit de uñas','gel para uñas'],
    'ecommerceTerms':['Makartt Polygel Nail Kit','LKE Gel Nail Polish Set'],
    'commonSearchPhrases':['kit uñas gel precio','polygel comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'dermapen', 'productName':'Dermapen / Microneedling / Dermaroller', 'categoryId':'beauty_devices',
    'aliases':['dermapen','microneedling','dermaroller','dr pen'],
    'misspellings':['derma pen'],
    'englishTerms':['dermapen','microneedling pen','dermaroller 0.5mm'],
    'spanishTerms':['dermapen','microagujamiento'],
    'ecommerceTerms':['Dr. Pen Ultima A6 Pro','DermaBoss Derma Roller'],
    'commonSearchPhrases':['dermapen precio','dermaroller comprar'],
    'riskOverrideFlags':['medical'],
    'customerHint':'Este dispositivo médico-estético puede requerir revisión.',
    'adminHint':'Verificar clasificación médica o cosmética.' },

  { 'productKey':'led_mask', 'productName':'Mascarilla LED / Red Light Therapy', 'categoryId':'beauty_devices',
    'aliases':['mascarilla led','led therapy mask','luz roja facial','red light mask'],
    'misspellings':['mascara led facial'],
    'englishTerms':['led face mask','red light therapy device'],
    'spanishTerms':['mascarilla de luz led','terapia de luz roja'],
    'ecommerceTerms':['Currentbody Skin LED Light Therapy Mask','Project E Beauty LED Mask'],
    'commonSearchPhrases':['mascarilla led precio','red light therapy comprar'],
    'riskOverrideFlags':['medical'], 'customerHint':'', 'adminHint':'Verificar clasificación médica.' },

  # ══ MORE HOME ═════════════════════════════════════════════════════════════
  { 'productKey':'colchon_importado', 'productName':'Colchón / Topper / Memory Foam', 'categoryId':'home_decor_storage',
    'aliases':['colchón','topper colchón','memory foam mattress','casper mattress'],
    'misspellings':['colchon de memoria'],
    'englishTerms':['memory foam mattress','mattress topper','bed in a box'],
    'spanishTerms':['colchón de espuma','topper para cama'],
    'ecommerceTerms':['Casper Original Foam Mattress','Lucid 2-inch Memory Foam Topper'],
    'commonSearchPhrases':['colchón memory foam precio','mattress topper comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño y peso del artículo.', 'adminHint':'Verificar dimensiones y peso.' },

  { 'productKey':'almohada_ergonomica', 'productName':'Almohada Ergonómica / Cervical / Coop', 'categoryId':'home_decor_storage',
    'aliases':['almohada ergonómica','cervical pillow','coop home goods','memory foam pillow'],
    'misspellings':['almohada ergonomica'],
    'englishTerms':['cervical pillow','adjustable memory foam pillow'],
    'spanishTerms':['almohada cervical','almohada ergonómica'],
    'ecommerceTerms':['Coop Home Goods Original Pillow','Tempur-Pedic TEMPUR-Cloud Pillow'],
    'commonSearchPhrases':['almohada ergonómica precio','cervical pillow comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'set_cubiertos_acero', 'productName':'Set Cubiertos Acero / Vajilla / WMF', 'categoryId':'home_kitchen_appliances',
    'aliases':['set cubiertos','vajilla','wmf','christofle','cubiertos acero inox'],
    'misspellings':['juego de cubiertos'],
    'englishTerms':['flatware set','cutlery set stainless'],
    'spanishTerms':['juego de cubiertos','vajilla'],
    'ecommerceTerms':['WMF Spaten 6-Piece Flatware Set','Oneida 18/10 Stainless Flatware'],
    'commonSearchPhrases':['set cubiertos precio','vajilla comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'freidora_smoker', 'productName':'Parrilla / Smoker / Weber / Kamado', 'categoryId':'home_kitchen_appliances',
    'aliases':['parrilla weber','smoker bbq','kamado','parrilla de carbón'],
    'misspellings':['parrilla webers'],
    'englishTerms':['weber grill','smoker bbq','kamado grill'],
    'spanishTerms':['parrilla','asador bbq'],
    'ecommerceTerms':["Weber Original Kettle 22\"","Char-Broil Offset Smoker"],
    'commonSearchPhrases':['parrilla precio','weber grill comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño y peso.', 'adminHint':'Verificar peso y dimensiones.' },

  { 'productKey':'maquina_coser', 'productName':'Máquina de Coser / Singer / Brother', 'categoryId':'home_kitchen_appliances',
    'aliases':['máquina de coser','singer','brother cs6000i','sewing machine'],
    'misspellings':['maquina de cocer'],
    'englishTerms':['sewing machine','singer simple','brother cs6000i'],
    'spanishTerms':['máquina de coser'],
    'ecommerceTerms':["Singer 4452 Heavy Duty Sewing Machine","Brother CS6000i Computerized"],
    'commonSearchPhrases':['máquina de coser precio','singer comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'organizador_cables', 'productName':'Organizador de Cables / Cable Management', 'categoryId':'home_decor_storage',
    'aliases':['organizador cables','cable management','canaleta cables','velcro cables'],
    'misspellings':['organizador de cables'],
    'englishTerms':['cable organizer','cable management box','velcro cable ties'],
    'spanishTerms':['organizador de cables','canaleta'],
    'ecommerceTerms':['BLUELOUNGE CableBox','Joto Cable Organizer Box'],
    'commonSearchPhrases':['organizador cables precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'lampara_escritorio', 'productName':'Lámpara Escritorio / LED / Arquitecto', 'categoryId':'home_decor_storage',
    'aliases':['lámpara escritorio','desk lamp','lámpara led escritorio','lamp benq'],
    'misspellings':['lampara de escritorio'],
    'englishTerms':['desk lamp led','architect floor lamp'],
    'spanishTerms':['lámpara de escritorio','lámpara de trabajo'],
    'ecommerceTerms':["BenQ ScreenBar Monitor Lamp","TaoTronics LED Desk Lamp"],
    'commonSearchPhrases':['lámpara escritorio precio','desk lamp comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE SPORTS ═══════════════════════════════════════════════════════════
  { 'productKey':'tabla_surf', 'productName':'Tabla de Surf / Bodyboard / Paddle Board', 'categoryId':'sports_outdoor_variable',
    'aliases':['tabla surf','surfboard','bodyboard','paddle board sup'],
    'misspellings':['tabla de surf'],
    'englishTerms':['surfboard','foam surfboard','paddle board sup'],
    'spanishTerms':['tabla de surf','paddle board'],
    'ecommerceTerms':["Wavestorm 8' Classic Foam Surfboard","iROCKER All Around 11' SUP"],
    'commonSearchPhrases':['tabla surf precio','paddle board comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño.', 'adminHint':'Verificar dimensiones.' },

  { 'productKey':'esquis_snowboard', 'productName':'Esquís / Snowboard / Botas Snowboard', 'categoryId':'sports_outdoor_variable',
    'aliases':['snowboard','esquís','botas snowboard','ski gear'],
    'misspellings':['snowboard tabla'],
    'englishTerms':['snowboard','ski equipment','burton snowboard'],
    'spanishTerms':['snowboard','esquís'],
    'ecommerceTerms':["Burton Custom Snowboard","Rossignol Experience 86 Ti Skis"],
    'commonSearchPhrases':['snowboard precio','ski gear comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño.', 'adminHint':'Verificar dimensiones.' },

  { 'productKey':'zapatillas_trail', 'productName':'Zapatillas Trail Running / Salomon / Hoka', 'categoryId':'footwear_complete',
    'aliases':['zapatillas trail','salomon trail','hoka clifton','trail running shoes'],
    'misspellings':['zapatillas de trail'],
    'englishTerms':['trail running shoes','salomon speedcross 6','hoka clifton 9'],
    'spanishTerms':['zapatillas trail','zapatos de montaña'],
    'ecommerceTerms':['Salomon Speedcross 6 Trail','Hoka Clifton 9','Brooks Cascadia 17'],
    'commonSearchPhrases':['zapatillas trail precio','salomon comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'mancuernas_hierro', 'productName':'Mancuernas / Kettlebell / Hierro Fundido', 'categoryId':'sports_fitness_physical',
    'aliases':['mancuernas','dumbbells','kettlebell','pesas hierro fundido'],
    'misspellings':['mancuernas de hierro'],
    'englishTerms':['dumbbells set','kettlebell cast iron'],
    'spanishTerms':['mancuernas','pesas de hierro'],
    'ecommerceTerms':['CAP Barbell Rubber Hex Dumbbell Pair','Kettlebell Kings 35 lb'],
    'commonSearchPhrases':['mancuernas precio','dumbbells comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el peso considerable.', 'adminHint':'Verificar peso total.' },

  { 'productKey':'yoga_mat', 'productName':'Mat de Yoga / Pilates / Cork Mat', 'categoryId':'sports_fitness_physical',
    'aliases':['yoga mat','mat yoga','mat pilates','lululemon mat','manduka mat'],
    'misspellings':['mat de yoga'],
    'englishTerms':['yoga mat','non-slip yoga mat','manduka prolite'],
    'spanishTerms':['colchoneta yoga','mat de yoga'],
    'ecommerceTerms':['Lululemon The Reversible Mat 5mm','Manduka PRO Yoga Mat'],
    'commonSearchPhrases':['yoga mat precio','manduka mat comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'zapatillas_baloncesto', 'productName':'Zapatillas Baloncesto / Nike LeBron / KD', 'categoryId':'footwear_complete',
    'aliases':['zapatillas baloncesto','basketball shoes','nike lebron','kd shoes','adidas dame'],
    'misspellings':['zapatillas de basketball'],
    'englishTerms':['basketball shoes','nike lebron xx','kobe 6 protro'],
    'spanishTerms':['zapatillas de baloncesto','tenis de baloncesto'],
    'ecommerceTerms':["Nike LeBron XX","Adidas Harden Vol. 7","Nike Zoom KD16"],
    'commonSearchPhrases':['zapatillas baloncesto precio','nike lebron comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'bicicleta_electrica', 'productName':'Bicicleta Eléctrica / E-bike / Rad Power', 'categoryId':'sports_outdoor_variable',
    'aliases':['bicicleta eléctrica','e-bike','rad power bikes','ebike','veloped'],
    'misspellings':['bicicleta electrica'],
    'englishTerms':['electric bike','e-bike','rad power bikes radrunner'],
    'spanishTerms':['bicicleta eléctrica','e-bike'],
    'ecommerceTerms':['Rad Power Bikes RadRunner 3 Plus','Aventon Pace 500.3'],
    'commonSearchPhrases':['bicicleta eléctrica precio','e-bike comprar'],
    'riskOverrideFlags':['contains_lithium_battery'],
    'customerHint':'Las bicicletas eléctricas contienen batería de litio — pueden requerir revisión de transporte.',
    'adminHint':'Revisar normativa DG y capacidad Wh de la batería.' },

  # ══ MORE AUTOMOTIVE ═══════════════════════════════════════════════════════
  { 'productKey':'camara_trasera', 'productName':'Cámara Trasera / Reverse Camera / 360°', 'categoryId':'automotive_simple_accessories',
    'aliases':['cámara trasera','reverse camera','backup camera','cámara 360 carro'],
    'misspellings':['camara de reversa'],
    'englishTerms':['backup camera','reverse camera','360 degree car camera'],
    'spanishTerms':['cámara de reversa','cámara trasera auto'],
    'ecommerceTerms':['AMTIFO FHD Backup Camera','Garmin BC 50 Wireless Backup Camera'],
    'commonSearchPhrases':['cámara trasera carro precio','backup camera comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'asiento_carro_nino', 'productName':'Silla de Carro Niño / Car Seat / Maxi-Cosi', 'categoryId':'baby_items',
    'aliases':['silla carro niño','car seat','maxi-cosi','chicco car seat','silla bebé carro'],
    'misspellings':['silla de carro niño'],
    'englishTerms':['convertible car seat','infant car seat','maxi-cosi pria'],
    'spanishTerms':['silla de auto para bebé','silla de carro'],
    'ecommerceTerms':['Maxi-Cosi Pria All-in-One','Chicco KeyFit 35','Graco 4Ever DLX'],
    'commonSearchPhrases':['silla carro niño precio','car seat comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cargador_carro', 'productName':'Cargador Rápido para Carro / Dual USB-C', 'categoryId':'automotive_simple_accessories',
    'aliases':['cargador para carro','car charger','cargador usb carro','car fast charger'],
    'misspellings':['cargador de carro'],
    'englishTerms':['car charger','dual usb-c car charger','fast charge car adapter'],
    'spanishTerms':['cargador para carro','adaptador usb carro'],
    'ecommerceTerms':['Anker 40W Dual USB-C Car Charger','Belkin Car Charger Dual USB'],
    'commonSearchPhrases':['cargador carro precio','car charger comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'filtro_aceite', 'productName':'Filtro de Aceite / Air Filter / Cabin Filter', 'categoryId':'automotive_parts_review',
    'aliases':['filtro aceite','oil filter','air filter carro','cabin air filter'],
    'misspellings':['filtro de aceite'],
    'englishTerms':['oil filter','engine air filter','cabin air filter'],
    'spanishTerms':['filtro de aceite','filtro de aire'],
    'ecommerceTerms':["Bosch 3500 Premium FILTECH Oil Filter","K&N High Performance Air Filter"],
    'commonSearchPhrases':['filtro aceite precio','oil filter comprar'],
    'riskOverrideFlags':['automotive_part_review'], 'customerHint':'Requiere revisión por clasificación arancelaria.', 'adminHint':'Validar clasificación.' },

  # ══ MORE GAMING ═══════════════════════════════════════════════════════════
  { 'productKey':'steering_wheel', 'productName':'Volante Racing / Logitech G29 / Fanatec', 'categoryId':'gaming_physical_accessories',
    'aliases':['volante gaming','logitech g29','fanatec','racing wheel','pedals'],
    'misspellings':['volante de racing'],
    'englishTerms':['racing wheel','logitech g29','fanatec podium'],
    'spanishTerms':['volante de carreras','racing wheel'],
    'ecommerceTerms':['Logitech G29 Driving Force','Thrustmaster T248'],
    'commonSearchPhrases':['volante gaming precio','logitech g29 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'arcade_joystick', 'productName':'Arcade Stick / Joystick / Hitbox', 'categoryId':'gaming_physical_accessories',
    'aliases':['arcade stick','joystick','hitbox controller','fighting stick'],
    'misspellings':['arcade stik'],
    'englishTerms':['arcade stick','fighting joystick','hitbox controller'],
    'spanishTerms':['arcade stick','palanca de juego'],
    'ecommerceTerms':['Razer Kitsune Arcade Controller','Hori Real Arcade Pro 4 Kai'],
    'commonSearchPhrases':['arcade stick precio','joystick comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'gaming_router', 'productName':'Router Gaming / ASUS ROG / Killer WiFi', 'categoryId':'networking_equipment',
    'aliases':['router gaming','asus rog router','rog rapture','killer wifi router'],
    'misspellings':['router gaming asus'],
    'englishTerms':['gaming router','asus rog rapture gt-ax11000'],
    'spanishTerms':['router para gaming','router gaming'],
    'ecommerceTerms':['ASUS ROG Rapture GT-AX11000','Netgear Nighthawk Pro Gaming XR1000'],
    'commonSearchPhrases':['router gaming precio','rog rapture comprar'],
    'riskOverrideFlags':['telecom_possible'], 'customerHint':'', 'adminHint':'Verificar homologación SUTEL.' },

  { 'productKey':'captura_elgato', 'productName':'Tarjeta Captura / Elgato / Razer Ripsaw', 'categoryId':'gaming_physical_accessories',
    'aliases':['captura elgato','elgato hd60','razer ripsaw','capture card','tarjeta captura'],
    'misspellings':['elgato captura'],
    'englishTerms':['capture card','elgato 4k60 pro','razer ripsaw hd'],
    'spanishTerms':['tarjeta de captura','capturadora de video'],
    'ecommerceTerms':['Elgato 4K60 Pro MK.2','Razer Ripsaw HD USB Capture Card'],
    'commonSearchPhrases':['capture card precio','elgato comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE TOYS / BABY ══════════════════════════════════════════════════════
  { 'productKey':'juguete_madera', 'productName':'Juguete de Madera / Montessori / Hape', 'categoryId':'toys_common',
    'aliases':['juguete madera','montessori juguete madera','hape toys','wooden toys'],
    'misspellings':['juguete de madera montessori'],
    'englishTerms':['wooden montessori toys','hape play'],
    'spanishTerms':['juguete de madera','juguete montessori'],
    'ecommerceTerms':["Hape Quadrilla Marble Run","Melissa & Doug Shape Sorting Cube"],
    'commonSearchPhrases':['juguete madera precio','montessori toy comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'figura_coleccion', 'productName':'Figura Coleccionable / Funko Pop / Nendoroid', 'categoryId':'toys_common',
    'aliases':['funko pop','nendoroid','figura coleccionable','action figure'],
    'misspellings':['funko pops'],
    'englishTerms':['funko pop vinyl','nendoroid figure','action figure'],
    'spanishTerms':['figura coleccionable','funko pop'],
    'ecommerceTerms':['Funko Pop Vinyl Figure','Good Smile Nendoroid'],
    'commonSearchPhrases':['funko pop precio','figura coleccionable comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'lego_ideas', 'productName':'LEGO Ideas / Creator Expert / UCS', 'categoryId':'toys_common',
    'aliases':['lego ideas','lego creator expert','lego ucs','lego adulto coleccionista'],
    'misspellings':['lego ideas set'],
    'englishTerms':['lego ideas','lego creator expert','lego ucs set'],
    'spanishTerms':['lego ideas','lego coleccionable'],
    'ecommerceTerms':["LEGO Ideas Vincent van Gogh - The Starry Night","LEGO Creator Expert Eiffel Tower"],
    'commonSearchPhrases':['lego ideas precio','lego creator expert comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'hamaca_bebe', 'productName':'Hamaca Bebé / Bouncer / Baby Swing', 'categoryId':'baby_items',
    'aliases':['hamaca bebé','bouncer bebé','baby swing','columpio bebé'],
    'misspellings':['hamaca de bebe'],
    'englishTerms':['baby bouncer','baby swing','mamaroo'],
    'spanishTerms':['mecedora bebé','hamaca para bebé'],
    'ecommerceTerms':['4moms MamaRoo 4 Infant Seat','Fisher-Price Snugapuppy Deluxe Bouncer'],
    'commonSearchPhrases':['bouncer bebé precio','mamaroo comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'monitor_bebe', 'productName':'Monitor de Bebé / Baby Monitor / Nanit', 'categoryId':'baby_items',
    'aliases':['monitor bebé','baby monitor','nanit','owlet cam','hello baby monitor'],
    'misspellings':['monitor de bebe'],
    'englishTerms':['baby monitor','nanit pro camera','eufy spaceview'],
    'spanishTerms':['monitor para bebé','intercomunicador bebé'],
    'ecommerceTerms':['Nanit Pro Smart Baby Monitor','Eufy SpaceView Baby Monitor'],
    'commonSearchPhrases':['monitor bebé precio','nanit comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE SUPPLEMENTS / HEALTH ═════════════════════════════════════════════
  { 'productKey':'omega3', 'productName':'Omega-3 / Fish Oil / Krill Oil', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['omega 3','fish oil','krill oil','aceite de pescado'],
    'misspellings':['omega3 fish oil'],
    'englishTerms':['omega-3 fish oil','krill oil supplement'],
    'spanishTerms':['omega 3','aceite de pescado'],
    'ecommerceTerms':["Nordic Naturals Ultimate Omega","Sports Research Krill Oil"],
    'commonSearchPhrases':['omega 3 precio','fish oil comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos pueden requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA.' },

  { 'productKey':'probioticos', 'productName':'Probióticos / Lactobacillus / Garden of Life', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['probióticos','probiotics','lactobacillus','garden of life probiotics'],
    'misspellings':['probioticos'],
    'englishTerms':['probiotics supplement','garden of life dr. formulated'],
    'spanishTerms':['probióticos','flora intestinal'],
    'ecommerceTerms':['Garden of Life Dr. Formulated Probiotics','Ritual Synbiotic+'],
    'commonSearchPhrases':['probióticos precio','probiotics comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos pueden requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA.' },

  { 'productKey':'pre_workout', 'productName':'Pre-Workout / Energizante Deportivo', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['pre workout','pre-workout','cellucor c4','ghost pre workout'],
    'misspellings':['pre workout deportivo'],
    'englishTerms':['pre-workout supplement','cellucor c4 pre-workout'],
    'spanishTerms':['pre-entrenamiento','energizante deportivo'],
    'ecommerceTerms':['Cellucor C4 Original Pre Workout','Ghost Legend Pre-Workout'],
    'commonSearchPhrases':['pre workout precio','c4 comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Este suplemento puede requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA para estimulantes.' },

  { 'productKey':'glutamina', 'productName':'Glutamina / L-Glutamine / Recuperación', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['glutamina','l-glutamine','glutamine powder'],
    'misspellings':['glutamina powder'],
    'englishTerms':['l-glutamine','glutamine supplement'],
    'spanishTerms':['glutamina','glutamina en polvo'],
    'ecommerceTerms':['NOW Sports L-Glutamine Powder 1lb','Optimum Nutrition Glutamine'],
    'commonSearchPhrases':['glutamina precio','l-glutamine comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos pueden requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA.' },

  { 'productKey':'vitamina_c_supl', 'productName':'Vitamina C / Zinc / Immune Support', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['vitamina c','zinc supplement','immune support vitamins','vitamin c 1000mg'],
    'misspellings':['vitamina C zinc'],
    'englishTerms':['vitamin c 1000mg','zinc supplement','immune support'],
    'spanishTerms':['vitamina c','soporte inmune'],
    'ecommerceTerms':["Nature's Way Vitamin C 1000mg","Thorne Zinc Picolinate"],
    'commonSearchPhrases':['vitamina c precio','zinc supplement comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos pueden requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA.' },

  { 'productKey':'ashwagandha', 'productName':'Ashwagandha / Adaptógenos / Nootropics', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['ashwagandha','adaptógenos','nootropics','lion mane mushroom','shilajit'],
    'misspellings':['ashwagandha supplement'],
    'englishTerms':["ashwagandha ksm-66","lion's mane mushroom"],
    'spanishTerms':['ashwagandha','adaptógenos'],
    'ecommerceTerms':["KSM-66 Ashwagandha","Four Sigmatic Lion's Mane Elixir"],
    'commonSearchPhrases':['ashwagandha precio','nootropics comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos pueden requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA para adaptógenos.' },

  # ══ MEDICINES / MEDICAL DEVICES ═══════════════════════════════════════════
  { 'productKey':'nebulizador', 'productName':'Nebulizador / Inhalador / CPAP', 'categoryId':'medicines_medical_products',
    'aliases':['nebulizador','inhalador','cpap machine','nebulizer'],
    'misspellings':['nebulizador médico'],
    'englishTerms':['nebulizer','cpap machine','portable nebulizer'],
    'spanishTerms':['nebulizador','inhalador'],
    'ecommerceTerms':['Omron NE-C801 Nebulizer','Drive Medical IntelliPAP AutoCPAP'],
    'commonSearchPhrases':['nebulizador precio','cpap comprar'],
    'riskOverrideFlags':['medical','sanitary_review'],
    'customerHint':'Los dispositivos médicos pueden requerir registro sanitario.',
    'adminHint':'Verificar registro CCSS/MINSA.' },

  { 'productKey':'termometro_digital', 'productName':'Termómetro Digital / Infrarrojo / Frente', 'categoryId':'medicines_medical_products',
    'aliases':['termómetro digital','termómetro infrarrojo','termómetro de frente','digital thermometer'],
    'misspellings':['termometro digital'],
    'englishTerms':['digital thermometer','infrared forehead thermometer'],
    'spanishTerms':['termómetro digital','termómetro de frente'],
    'ecommerceTerms':['Braun No-Touch Forehead Thermometer','Withings Thermo Smart Temporal'],
    'commonSearchPhrases':['termómetro precio','termómetro infrarrojo comprar'],
    'riskOverrideFlags':['medical'], 'customerHint':'', 'adminHint':'Verificar clasificación médica.' },

  { 'productKey':'colchoneta_viscoelastica', 'productName':'Colchón Viscoelástico / Ortopédico / Emma', 'categoryId':'home_decor_storage',
    'aliases':['colchón viscoelástico','emma mattress','nectar mattress','colchón ortopédico'],
    'misspellings':['colchon viscoelastico'],
    'englishTerms':['memory foam mattress','emma mattress','nectar memory foam'],
    'spanishTerms':['colchón de espuma viscoelástica','colchón ortopédico'],
    'ecommerceTerms':['Emma Original Mattress','Nectar Memory Foam Mattress'],
    'commonSearchPhrases':['colchón viscoelástico precio','emma mattress comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño y peso.', 'adminHint':'Verificar dimensiones y peso.' },

  # ══ ADDITIONAL MISC ═══════════════════════════════════════════════════════
  { 'productKey':'teclado_numerico', 'productName':'Teclado Numérico / Numpad / Calculator', 'categoryId':'computer_accessories',
    'aliases':['teclado numérico','numpad','numpad bluetooth','ten key numpad'],
    'misspellings':['numpad teclado'],
    'englishTerms':['numeric keypad','numpad bluetooth','ten key'],
    'spanishTerms':['teclado numérico','numpad'],
    'ecommerceTerms':['Jelly Comb Wireless Numeric Keypad','Logitech MX Keys Plus'],
    'commonSearchPhrases':['teclado numérico precio','numpad comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'monitor_arm_dual', 'productName':'Brazo Doble Monitor / Ergotron LX Dual', 'categoryId':'computer_accessories',
    'aliases':['brazo doble monitor','dual monitor arm','ergotron dual','soporte doble pantalla'],
    'misspellings':['brazo de monitor doble'],
    'englishTerms':['dual monitor arm','ergotron lx dual desk mount'],
    'spanishTerms':['soporte doble monitor','brazo para dos monitores'],
    'ecommerceTerms':['Ergotron LX Dual Stacking Arm','Vivo Dual LCD Monitor Mount'],
    'commonSearchPhrases':['brazo doble monitor precio','dual monitor arm comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'iphone_15', 'productName':'iPhone 15 / 15 Plus / 15 Pro Max', 'categoryId':'phones_smartphones',
    'aliases':['iphone 15','iphone 15 pro','iphone 15 pro max','apple iphone 15'],
    'misspellings':['iphon 15','iphone15 pro'],
    'englishTerms':['iphone 15','iphone 15 pro max','apple iphone 15 plus'],
    'spanishTerms':['celular apple iphone 15','iphone 15 pro'],
    'ecommerceTerms':['Apple iPhone 15 Pro Max 256GB','Apple iPhone 15 128GB'],
    'commonSearchPhrases':['iphone 15 precio','iphone 15 pro max comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'iphone_16', 'productName':'iPhone 16 / 16 Pro / 16 Pro Max', 'categoryId':'phones_smartphones',
    'aliases':['iphone 16','iphone 16 pro','iphone 16 pro max'],
    'misspellings':['iphone16','iphon 16'],
    'englishTerms':['iphone 16','iphone 16 pro max'],
    'spanishTerms':['celular apple iphone 16'],
    'ecommerceTerms':['Apple iPhone 16 Pro Max','Apple iPhone 16 128GB'],
    'commonSearchPhrases':['iphone 16 precio','iphone 16 pro max comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'samsung_s25', 'productName':'Samsung Galaxy S25 / S25 Ultra', 'categoryId':'phones_smartphones',
    'aliases':['samsung s25','galaxy s25','s25 ultra','samsung galaxy s25'],
    'misspellings':['sansung s25','galaxy s 25'],
    'englishTerms':['samsung galaxy s25','galaxy s25 ultra'],
    'spanishTerms':['celular samsung s25'],
    'ecommerceTerms':['Samsung Galaxy S25 Ultra','Samsung Galaxy S25+'],
    'commonSearchPhrases':['samsung s25 precio','galaxy s25 ultra comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cargador_magsafe_15w', 'productName':'Cargador MagSafe 15W / iPhone USB-C', 'categoryId':'chargers_cables_adapters',
    'aliases':['magsafe 15w','cargador magsafe','apple 20w adapter','apple charger'],
    'misspellings':['magsafe cargador'],
    'englishTerms':['apple magsafe 15w charger','apple 20w usb-c adapter'],
    'spanishTerms':['cargador magsafe apple','adaptador apple'],
    'ecommerceTerms':['Apple MagSafe Charger 15W','Apple 20W USB-C Power Adapter'],
    'commonSearchPhrases':['magsafe 15w precio','apple charger comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'audifonos_osito', 'productName':'Audífonos Niños / Kids Headphones / Puro Sound', 'categoryId':'headphones_audio_personal',
    'aliases':['audífonos niños','kids headphones','puro sound labs','headset infantil'],
    'misspellings':['audifonos de niños'],
    'englishTerms':['kids headphones','volume limited headphones for kids'],
    'spanishTerms':['audífonos para niños','cascos infantiles'],
    'ecommerceTerms':['Puro Sound Labs BT2200 Kids Headphones','JLab JBuddies Studio Wired Kids'],
    'commonSearchPhrases':['audífonos niños precio','kids headphones comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'mochila_gaming', 'productName':'Mochila Gamer / Laptop Bag / ASUS ROG Bag', 'categoryId':'bags_luggage_accessories',
    'aliases':['mochila gamer','asus rog bag','razer tactical bag','laptop bag gaming'],
    'misspellings':['mochila gaming'],
    'englishTerms':['gaming laptop bag','asus rog backpack','razer tactical backpack'],
    'spanishTerms':['mochila para gamer','mochila laptop gaming'],
    'ecommerceTerms':['ASUS ROG Ranger BP4701 Backpack','Razer Rogue 17 Backpack V3'],
    'commonSearchPhrases':['mochila gamer precio','rog backpack comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'guitarra_electrica', 'productName':'Guitarra Eléctrica / Fender / Gibson', 'categoryId':'microphones_audio_pro',
    'aliases':['guitarra eléctrica','fender stratocaster','gibson les paul','guitarra electrica'],
    'misspellings':['guitarra electrica fender'],
    'englishTerms':['electric guitar','fender player stratocaster','gibson les paul standard'],
    'spanishTerms':['guitarra eléctrica'],
    'ecommerceTerms':['Fender Player Stratocaster','Gibson Les Paul Standard','Epiphone Les Paul Standard'],
    'commonSearchPhrases':['guitarra eléctrica precio','fender stratocaster comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño y peso.', 'adminHint':'Verificar dimensiones.' },

  { 'productKey':'alcohol_isopropilico', 'productName':'Alcohol Isopropílico / IPA / Limpieza', 'categoryId':'chemicals_aerosols_adhesives',
    'aliases':['alcohol isopropílico','isopropyl alcohol','ipa 99','alcohol limpieza electrónica'],
    'misspellings':['alcohol isopropilico'],
    'englishTerms':['isopropyl alcohol 99%','ipa cleaning solution'],
    'spanishTerms':['alcohol isopropílico','IPA para electrónica'],
    'ecommerceTerms':['MG Chemicals 824-1L IPA','Amazon Basics 99% Isopropyl Alcohol'],
    'commonSearchPhrases':['alcohol isopropílico precio'],
    'riskOverrideFlags':['chemical','flammable'],
    'customerHint':'Este producto es inflamable y puede tener restricciones de transporte.',
    'adminHint':'Revisar normativa de líquidos inflamables.' },

  { 'productKey':'soldadura_estano', 'productName':'Soldadura de Estaño / Flux / Rework Station', 'categoryId':'chemicals_aerosols_adhesives',
    'aliases':['soldadura estaño','solder wire','flux paste','rework station'],
    'misspellings':['soldadura de estaño'],
    'englishTerms':['solder wire','rosin flux paste','hot air rework station'],
    'spanishTerms':['soldadura de estaño','pasta de flux'],
    'ecommerceTerms':['Kester 44 Rosin Core Solder','Amtech NC-559-V2-TF Flux'],
    'commonSearchPhrases':['soldadura estaño precio','flux paste comprar'],
    'riskOverrideFlags':['chemical'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'libro_recetas', 'productName':'Libro de Recetas / Cookbook / Ottolenghi', 'categoryId':'books_printed_material',
    'aliases':['libro recetas','cookbook','ottolenghi','libro cocina'],
    'misspellings':['libro de recetas'],
    'englishTerms':['cookbook','ottolenghi jerusalem','salt fat acid heat'],
    'spanishTerms':['libro de cocina','recetario'],
    'ecommerceTerms':['Salt Fat Acid Heat by Samin Nosrat','Ottolenghi Simple'],
    'commonSearchPhrases':['libro de recetas precio','cookbook comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'papel_fotografia', 'productName':'Papel Fotográfico / Impresión / Canon Papel', 'categoryId':'office_stationery_art',
    'aliases':['papel fotográfico','photo paper','canon foto papel','epson photo paper'],
    'misspellings':['papel fotografico'],
    'englishTerms':['photo paper glossy','inkjet photo paper'],
    'spanishTerms':['papel fotográfico','papel para fotos'],
    'ecommerceTerms':['Canon Photo Paper Plus Glossy II','Epson S041271 Photo Paper'],
    'commonSearchPhrases':['papel fotográfico precio','photo paper comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'tinta_impresora', 'productName':'Tinta / Cartucho de Tinta / Tóner', 'categoryId':'office_stationery_art',
    'aliases':['tinta impresora','cartucho tinta','tóner','ink cartridge'],
    'misspellings':['tinta para impresora'],
    'englishTerms':['ink cartridge','laser toner','printer ink'],
    'spanishTerms':['tinta para impresora','cartucho de tinta'],
    'ecommerceTerms':['HP 65XL Black Ink Cartridge','Canon PG-245XL Ink'],
    'commonSearchPhrases':['tinta impresora precio','cartucho tinta comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'pintura_acrilica', 'productName':'Pintura Acrílica / Óleo / Golden / Winsor', 'categoryId':'office_stationery_art',
    'aliases':['pintura acrílica','pintura al óleo','golden acrylics','winsor newton'],
    'misspellings':['pintura acrilica'],
    'englishTerms':['acrylic paint set','oil paint','golden heavy body acrylics'],
    'spanishTerms':['pintura acrílica','pintura al óleo'],
    'ecommerceTerms':["Golden Heavy Body Acrylic 5oz","Winsor & Newton Artist Oil 37ml"],
    'commonSearchPhrases':['pintura acrílica precio','golden acrylics comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'destornillador_electrico', 'productName':'Destornillador Eléctrico / iFixit / Wowstick', 'categoryId':'tools_hardware_common',
    'aliases':['destornillador eléctrico','wowstick','ifixit precision','electric screwdriver'],
    'misspellings':['destonillador electrico'],
    'englishTerms':['electric screwdriver','wowstick 1f+','ifixit precision driver'],
    'spanishTerms':['destornillador eléctrico','atornillador automático'],
    'ecommerceTerms':['Wowstick 1F+ Electric Screwdriver','iFixit Pro Tech Toolkit'],
    'commonSearchPhrases':['destornillador eléctrico precio','wowstick comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'medidor_laser', 'productName':'Medidor Láser / Distanciómetro / Bosch', 'categoryId':'tools_hardware_common',
    'aliases':['medidor láser','distanciómetro','laser measure','bosch glm'],
    'misspellings':['medidor laser'],
    'englishTerms':['laser distance meter','bosch glm 50','laser tape measure'],
    'spanishTerms':['medidor láser','distanciómetro'],
    'ecommerceTerms':['Bosch GLM 50 Laser Measure','Leica DISTO D2'],
    'commonSearchPhrases':['medidor láser precio','bosch glm comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'reloj_smartwatch_samsung', 'productName':'Samsung Galaxy Watch / Gear', 'categoryId':'watches_jewelry',
    'aliases':['samsung galaxy watch','galaxy watch 6','galaxy watch ultra','samsung gear'],
    'misspellings':['samsung galaxy watch 6'],
    'englishTerms':['samsung galaxy watch 6','galaxy watch ultra'],
    'spanishTerms':['samsung galaxy watch','reloj samsung'],
    'ecommerceTerms':['Samsung Galaxy Watch 6 Classic','Samsung Galaxy Watch Ultra'],
    'commonSearchPhrases':['samsung galaxy watch precio','galaxy watch comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'drone_accesorios', 'productName':'Accesorios Dron / ND Filters / Extra Batteries', 'categoryId':'drones_rc_review',
    'aliases':['accesorios dron','nd filters dron','baterías extra dji','drone accessories'],
    'misspellings':['accesorios de dron'],
    'englishTerms':['drone nd filter set','dji mini 4 pro accessories','extra drone battery'],
    'spanishTerms':['accesorios para dron','filtros nd dji'],
    'ecommerceTerms':['DJI Mini 4 Pro ND Filters Set','DJI Fly More Combo Extra Battery'],
    'commonSearchPhrases':['accesorios dron precio'],
    'riskOverrideFlags':['battery_possible'],
    'customerHint':'Contiene baterías de litio — puede requerir revisión de transporte.',
    'adminHint':'Revisar Wh de baterías.' },

  { 'productKey':'ropa_bebe_set', 'productName':'Ropa Recién Nacido / Bodysuit / Set Bebé', 'categoryId':'baby_items',
    'aliases':['ropa bebé','bodysuit bebé','set ropa recién nacido','newborn clothes'],
    'misspellings':['ropa de bebe'],
    'englishTerms':['newborn baby clothes','baby bodysuit set'],
    'spanishTerms':['ropa para bebé recién nacido','bodys bebé'],
    'ecommerceTerms':["Carter's Baby Newborn 7-Piece Set","Gerber Onesies Bodysuits 8-Pack"],
    'commonSearchPhrases':['ropa bebé precio','bodysuit bebé comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'monitor_presion', 'productName':'Tensiómetro / Monitor de Presión Arterial', 'categoryId':'medicines_medical_products',
    'aliases':['tensiómetro','monitor presión arterial','blood pressure monitor','omron bp'],
    'misspellings':['tensionmetro'],
    'englishTerms':['blood pressure monitor','automatic bp cuff'],
    'spanishTerms':['tensiómetro','monitor de presión arterial'],
    'ecommerceTerms':['Omron Platinum Blood Pressure Monitor','Withings BPM Connect'],
    'commonSearchPhrases':['tensiómetro precio','monitor presión comprar'],
    'riskOverrideFlags':['medical'], 'customerHint':'', 'adminHint':'Verificar clasificación médica.' },

  { 'productKey':'ropa_ciclismo_set', 'productName':'Conjunto Ciclismo / Bib Shorts / Jersey', 'categoryId':'sports_outdoor_variable',
    'aliases':['conjunto ciclismo','bib shorts','jersey ciclismo','cycling kit'],
    'misspellings':['conjunto de ciclismo'],
    'englishTerms':['cycling bib shorts','cycling jersey','cycling kit'],
    'spanishTerms':['culote ciclismo','camiseta ciclismo'],
    'ecommerceTerms':['Castelli Free Aero Race 4 Bib Short','Rapha Core Cargo Bib Short'],
    'commonSearchPhrases':['conjunto ciclismo precio','bib shorts comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'zapatillas_running', 'productName':'Zapatillas Running / Nike Pegasus / ASICS Gel', 'categoryId':'footwear_complete',
    'aliases':['zapatillas running','nike pegasus','asics gel nimbus','brooks ghost'],
    'misspellings':['zapatillas de correr'],
    'englishTerms':['running shoes','nike air zoom pegasus','asics gel-nimbus 25'],
    'spanishTerms':['tenis para correr','zapatillas de running'],
    'ecommerceTerms':['Nike Air Zoom Pegasus 40','ASICS Gel-Nimbus 25','Brooks Ghost 15'],
    'commonSearchPhrases':['zapatillas running precio','nike pegasus comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'whey_isolate', 'productName':'Proteína Whey Isolate / Zero Carb', 'categoryId':'supplements_vitamins_nutrition',
    'aliases':['whey isolate','proteína isolada','dymatize iso 100','isopure whey'],
    'misspellings':['whey isolate proteina'],
    'englishTerms':['whey protein isolate','dymatize iso 100','isopure zero carb'],
    'spanishTerms':['proteína isolada','whey aislado'],
    'ecommerceTerms':['Dymatize ISO 100 Hydrolyzed 5lb','Isopure Zero Carb 3lb'],
    'commonSearchPhrases':['whey isolate precio','iso 100 comprar'],
    'riskOverrideFlags':['supplement','sanitary_review'],
    'customerHint':'Los suplementos pueden requerir validación sanitaria.',
    'adminHint':'Revisar CCSS/MINSA.' },

  { 'productKey':'streaming_mic_setup', 'productName':'Setup Streaming / Arm + Mic + Pop Filter', 'categoryId':'microphones_audio_pro',
    'aliases':['setup streaming','arm micrófono','pop filter','mic boom arm','rode psa1'],
    'misspellings':['setup de streaming'],
    'englishTerms':['microphone boom arm','pop filter','rode psa1 studio arm'],
    'spanishTerms':['brazo de micrófono','filtro pop'],
    'ecommerceTerms':['Rode PSA1 Boom Arm','InnoGear Microphone Arm','Mudder Pop Filter'],
    'commonSearchPhrases':['brazo micrófono precio','rode psa1 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'walkie_talkie_civil', 'productName':'Walkie Talkie Civil / PMR / FRS', 'categoryId':'regulated_telecom',
    'aliases':['walkie talkie','radio frs','pmr446','motorola talkabout'],
    'misspellings':['walkie talkie civil'],
    'englishTerms':['walkie talkie','frs radio','motorola talkabout'],
    'spanishTerms':['radio de comunicación','walkie-talkie'],
    'ecommerceTerms':['Motorola Solutions T800 Talkabout Radio','Midland GXT1000VP4'],
    'commonSearchPhrases':['walkie talkie precio','radio frs comprar'],
    'riskOverrideFlags':['telecom_possible'],
    'customerHint':'Los radios de comunicación pueden requerir revisión de la SUTEL.',
    'adminHint':'Verificar normativa SUTEL para PMR/FRS.' },

  { 'productKey':'libro_desarrollo_personal', 'productName':'Libro Desarrollo Personal / Finanzas / Mindset', 'categoryId':'books_printed_material',
    'aliases':['libro desarrollo personal','libro finanzas','mindset libro','atomic habits libro'],
    'misspellings':['libro de desarrollo personal'],
    'englishTerms':['self help book','personal finance book','atomic habits'],
    'spanishTerms':['libro de desarrollo personal','libro de finanzas'],
    'ecommerceTerms':['Atomic Habits by James Clear','The Psychology of Money','Deep Work'],
    'commonSearchPhrases':['libro atomic habits precio','desarrollo personal libro comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'repelente_mosquitos', 'productName':'Repelente Mosquitos / DEET / Citronella', 'categoryId':'chemicals_aerosols_adhesives',
    'aliases':['repelente mosquitos','deet spray','citronella','off spray'],
    'misspellings':['repelente de mosquitos'],
    'englishTerms':['mosquito repellent','deet spray','off deep woods'],
    'spanishTerms':['repelente de mosquitos','spray anti-mosquitos'],
    'ecommerceTerms':["OFF! Deep Woods Insect Repellent","Sawyer Products Premium Insect Repellent"],
    'commonSearchPhrases':['repelente mosquitos precio','deet comprar'],
    'riskOverrideFlags':['aerosol','chemical'],
    'customerHint':'Aerosol — puede tener restricciones de transporte.',
    'adminHint':'Revisar normativa aerosoles y pesticidas.' },

  { 'productKey':'headset_oficina', 'productName':'Headset para Oficina / Jabra / Poly / Teams', 'categoryId':'headphones_audio_personal',
    'aliases':['headset oficina','jabra evolve','poly voyager','microsoft teams headset'],
    'misspellings':['headset de oficina'],
    'englishTerms':['office headset','jabra evolve2 55','poly voyager focus 2'],
    'spanishTerms':['audífono para oficina','headset para llamadas'],
    'ecommerceTerms':['Jabra Evolve2 55 MS','Poly Voyager Focus 2 UC','Logitech Zone Wireless Plus'],
    'commonSearchPhrases':['headset oficina precio','jabra evolve comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'luz_uv_desinfeccion', 'productName':'Luz UV Desinfección / UV Sanitizer', 'categoryId':'medicines_medical_products',
    'aliases':['luz uv','uv sanitizer','germicidal uv lamp','desinfección uv'],
    'misspellings':['luz UV desinfectante'],
    'englishTerms':['uv sanitizer','germicidal uv light','uv-c light'],
    'spanishTerms':['lámpara uv germicida','desinfección luz uv'],
    'ecommerceTerms':['PhoneSoap Go UV Sanitizer','GermAwayUV Portable Wand'],
    'commonSearchPhrases':['luz uv precio','uv sanitizer comprar'],
    'riskOverrideFlags':['medical'], 'customerHint':'', 'adminHint':'Verificar clasificación.' },

  { 'productKey':'cable_hdmi', 'productName':'Cable HDMI / 4K / 8K / Mini HDMI', 'categoryId':'computer_accessories',
    'aliases':['cable hdmi','hdmi 4k','mini hdmi','hdmi 2.1','cable hdmi gaming'],
    'misspellings':['cable HDMI 4k'],
    'englishTerms':['hdmi 2.1 cable','4k hdmi cable','mini hdmi to hdmi'],
    'spanishTerms':['cable hdmi','cable de video hdmi'],
    'ecommerceTerms':['Belkin HDMI 2.1 Cable','Monoprice Ultra 8K Certified HDMI Cable'],
    'commonSearchPhrases':['cable hdmi 4k precio','hdmi 2.1 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'altavoz_smart', 'productName':'Altavoz Inteligente / HomePod / Echo Studio', 'categoryId':'speakers_home_audio',
    'aliases':['altavoz inteligente','homepod','echo studio','smart speaker'],
    'misspellings':['altavoz smart'],
    'englishTerms':['smart speaker','apple homepod','amazon echo studio'],
    'spanishTerms':['altavoz inteligente','bocina inteligente'],
    'ecommerceTerms':['Apple HomePod (2nd generation)','Amazon Echo Studio'],
    'commonSearchPhrases':['homepod precio','smart speaker comprar'],
    'riskOverrideFlags':['telecom_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'tablet_graficos_xp_pen', 'productName':'Tableta XP-Pen / Huion / Gaomon', 'categoryId':'computer_accessories',
    'aliases':['xp-pen','huion kamvas','gaomon','tableta gráfica xp pen'],
    'misspellings':['xp pen tableta'],
    'englishTerms':['xp-pen artist 12','huion kamvas pro 13'],
    'spanishTerms':['tableta gráfica xp-pen','xp pen'],
    'ecommerceTerms':['XP-PEN Artist 12 (2nd Gen)','Huion Kamvas 13 Gen 3'],
    'commonSearchPhrases':['xp-pen precio','huion kamvas comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'patron_costura', 'productName':'Patrón de Costura / Tela / Hilo / Bordado', 'categoryId':'office_stationery_art',
    'aliases':['patrón costura','tela importada','hilo bordado','embroidery kit'],
    'misspellings':['patron de costura'],
    'englishTerms':['sewing pattern','embroidery kit','fabric hilo'],
    'spanishTerms':['patrón de costura','kit de bordado'],
    'ecommerceTerms':["Simplicity Sewing Pattern","Bucilla Stamped Cross Stitch Kit"],
    'commonSearchPhrases':['patrón costura precio','embroidery kit comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

]

# ── Insert into JS ────────────────────────────────────────────────────────────

JS_MARKER = '    // ════════════════ TASK #384 EXPANSION ROWS ════════════════'

with open('js/product-categories.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

insert_pos = js_content.find(JS_MARKER)
if insert_pos == -1:
    print('ERROR: JS marker not found', file=sys.stderr); sys.exit(1)

# Insert batch 2 header just before batch 1 starts
new_js_block = '\n    // ════════════════ TASK #384 EXPANSION BATCH 2 ════════════════\n'
new_js_block += '\n'.join(row_to_js(r) for r in BATCH2)
new_js_block += '\n'

js_new = js_content[:insert_pos] + new_js_block + js_content[insert_pos:]

with open('js/product-categories.js', 'w', encoding='utf-8') as f:
    f.write(js_new)

print(f'JS: inserted {len(BATCH2)} rows in batch 2')

# ── Insert into JSON ──────────────────────────────────────────────────────────

with open('data/product-brain.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

for r in BATCH2:
    row = {
        'productKey': r['productKey'], 'productName': r['productName'],
        'categoryId': r['categoryId'],
        'aliases': r.get('aliases',[]), 'misspellings': r.get('misspellings',[]),
        'englishTerms': r.get('englishTerms',[]), 'spanishTerms': r.get('spanishTerms',[]),
        'ecommerceTerms': r.get('ecommerceTerms',[]),
        'commonSearchPhrases': r.get('commonSearchPhrases',[]),
        'riskOverrideFlags': r.get('riskOverrideFlags',[]),
        'customerHint': r.get('customerHint',''), 'adminHint': r.get('adminHint',''),
    }
    json_data['products'].append(row)

with open('data/product-brain.json', 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f'JSON: now has {len(json_data["products"])} products, {len(json_data["categories"])} categories')
