#!/usr/bin/env python3
"""Task #384 — Product Brain Expansion Batch 3 (~155 rows → total ~700+)."""
import json, sys

def q(s): return "'" + s.replace("'", "\\'") + "'"
def js_list(items): return '[' + ','.join(q(i) for i in items) + ']'

def row_to_js(r):
    parts = [
        f"productKey:{q(r['productKey'])}",
        f"productName:{q(r['productName'])}",
        f"categoryId:{q(r['categoryId'])}",
        f"aliases:{js_list(r.get('aliases',[]))}",
        f"misspellings:{js_list(r.get('misspellings',[]))}",
        f"englishTerms:{js_list(r.get('englishTerms',[]))}",
        f"spanishTerms:{js_list(r.get('spanishTerms',[]))}",
        f"ecommerceTerms:{js_list(r.get('ecommerceTerms',[]))}",
        f"commonSearchPhrases:{js_list(r.get('commonSearchPhrases',[]))}",
        f"riskOverrideFlags:{js_list(r.get('riskOverrideFlags',[]))}",
        f"customerHint:{q(r.get('customerHint',''))}",
        f"adminHint:{q(r.get('adminHint',''))}",
    ]
    return '    { ' + ', '.join(parts) + ' },'

BATCH3 = [

  # ══ MORE PHONES & ACCESSORIES ═════════════════════════════════════════════
  { 'productKey':'pixel_9', 'productName':'Google Pixel 9 / 9 Pro', 'categoryId':'phones_smartphones',
    'aliases':['pixel 9','google pixel 9','pixel 9 pro','pixel 9 pro xl'],
    'misspellings':['gogle pixel 9'],
    'englishTerms':['google pixel 9','pixel 9 pro xl'],
    'spanishTerms':['celular google pixel 9'],
    'ecommerceTerms':['Google Pixel 9 Pro','Google Pixel 9 128GB'],
    'commonSearchPhrases':['pixel 9 precio','google pixel 9 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'smartwatch_generic', 'productName':'Smartwatch Genérico / Fitbit / Amazfit', 'categoryId':'watches_jewelry',
    'aliases':['smartwatch','fitbit charge','amazfit gtr','reloj inteligente barato'],
    'misspellings':['smart watch'],
    'englishTerms':['fitbit charge 6','amazfit gtr 4','generic smartwatch'],
    'spanishTerms':['reloj inteligente','smartwatch barato'],
    'ecommerceTerms':['Fitbit Charge 6','Amazfit GTR 4','Xiaomi Smart Band 8'],
    'commonSearchPhrases':['smartwatch barato precio','fitbit charge comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cargador_solar_panel', 'productName':'Panel Solar Portátil / Cargador Solar 100W', 'categoryId':'chargers_cables_adapters',
    'aliases':['panel solar portátil','cargador solar 100w','solar panel folding'],
    'misspellings':['panel solar portatil'],
    'englishTerms':['portable solar panel','100w solar charger'],
    'spanishTerms':['panel solar portátil','cargador solar para camping'],
    'ecommerceTerms':['BigBlue 28W Solar Panel','Jackery SolarSaga 100W'],
    'commonSearchPhrases':['panel solar portátil precio','cargador solar comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'funda_laptop_sleeve', 'productName':'Funda Laptop / Sleeve / Maletín', 'categoryId':'bags_luggage_accessories',
    'aliases':['funda laptop','laptop sleeve','maletín laptop','laptop bag 15'],
    'misspellings':['funda para laptop'],
    'englishTerms':['laptop sleeve 15 inch','laptop briefcase'],
    'spanishTerms':['funda para laptop','maletín'],
    'ecommerceTerms':["Tomtoc Laptop Sleeve 15\"","Incase Icon Sleeve","Waterfield Designs Laptop Case"],
    'commonSearchPhrases':['funda laptop precio','laptop sleeve comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE CLOTHING (fill gaps) ══════════════════════════════════════════════
  { 'productKey':'chaqueta_cuero', 'productName':'Chaqueta de Cuero / Leather Jacket / Moto', 'categoryId':'clothing_general',
    'aliases':['chaqueta cuero','leather jacket','chaqueta motociclista','biker jacket'],
    'misspellings':['chaqueta de cuero'],
    'englishTerms':['leather jacket','biker jacket','moto jacket'],
    'spanishTerms':['chaqueta de cuero','chamarra de cuero'],
    'ecommerceTerms':["Schott NYC Perfecto Leather Motorcycle Jacket","AllSaints Cora Leather Jacket"],
    'commonSearchPhrases':['chaqueta cuero precio','leather jacket comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'sueter_tejido', 'productName':'Suéter Tejido / Knit Sweater / Cardigan', 'categoryId':'clothing_general',
    'aliases':['suéter tejido','knit sweater','cardigan','jersey de punto'],
    'misspellings':['sueter tejido'],
    'englishTerms':['knit sweater','chunky cardigan','crewneck sweater'],
    'spanishTerms':['suéter de punto','cardigan tejido'],
    'ecommerceTerms':["Everlane The Alpaca Crew","Mango Mohair-Effect Sweater"],
    'commonSearchPhrases':['suéter tejido precio','cardigan comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'tela_lino_seda', 'productName':'Ropa de Lino / Seda / Blusa Elegante', 'categoryId':'clothing_general',
    'aliases':['blusa seda','camisa lino','linen shirt','silk blouse'],
    'misspellings':['blusa de seda'],
    'englishTerms':['linen shirt','silk blouse','linen pants'],
    'spanishTerms':['camisa de lino','blusa de seda'],
    'ecommerceTerms':["Quince 100% European Linen Shirt","Equipment Silk Blouse"],
    'commonSearchPhrases':['camisa lino precio','silk blouse comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'ropa_maternidad', 'productName':'Ropa Maternidad / Embarazo / Nursing', 'categoryId':'clothing_general',
    'aliases':['ropa maternidad','maternity clothes','ropa embarazo','nursing bra'],
    'misspellings':['ropa de maternidad'],
    'englishTerms':['maternity dress','nursing bra','pregnancy clothes'],
    'spanishTerms':['ropa de maternidad','ropa para embarazadas'],
    'ecommerceTerms':["Seraphine Maternity Dress","Kindred Bravely Sublime Nursing Bra"],
    'commonSearchPhrases':['ropa maternidad precio','maternity dress comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'uniforme_escolar', 'productName':'Uniforme Escolar / Polo Escolar / Pants', 'categoryId':'clothing_general',
    'aliases':['uniforme escolar','polo escolar','pantalón escolar','school uniform'],
    'misspellings':['uniforme de escuela'],
    'englishTerms':['school uniform','school polo shirt','school pants'],
    'spanishTerms':['uniforme escolar','polo escolar'],
    'ecommerceTerms':['French Toast School Uniform Polo','Amazon Essentials School Polo'],
    'commonSearchPhrases':['uniforme escolar precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE HOME KITCHEN ══════════════════════════════════════════════════════
  { 'productKey':'sarten_ceramica', 'productName':'Sartén de Cerámica / Always Pan / Our Place', 'categoryId':'home_kitchen_appliances',
    'aliases':['sartén cerámica','always pan','our place pan','ceramic non-stick'],
    'misspellings':['sarten ceramica'],
    'englishTerms':['ceramic pan','our place always pan','non-stick ceramic'],
    'spanishTerms':['sartén de cerámica','sartén antiadherente cerámica'],
    'ecommerceTerms':["Our Place Always Pan 2.0","GreenPan Valencia Pro Ceramic"],
    'commonSearchPhrases':['sartén cerámica precio','always pan comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'jarra_agua_filtro', 'productName':'Jarra Filtro Agua / Brita / ZeroWater', 'categoryId':'home_kitchen_appliances',
    'aliases':['jarra filtro agua','brita filter','zerowater','pitcher filter'],
    'misspellings':['jarra de filtro agua'],
    'englishTerms':['water filter pitcher','brita standard pitcher'],
    'spanishTerms':['jarra con filtro','jarra purificadora'],
    'ecommerceTerms':['Brita Standard Water Filter Pitcher','ZeroWater 10-Cup Pitcher'],
    'commonSearchPhrases':['jarra filtro agua precio','brita comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'thermomix_rival', 'productName':'Robot de Cocina / Ninja Foodi / Thermomix', 'categoryId':'home_kitchen_appliances',
    'aliases':['thermomix','robot cocina','ninja foodi','magimix cook expert'],
    'misspellings':['thermolix','robot de cocina'],
    'englishTerms':['cooking robot','ninja foodi xl 14-in-1'],
    'spanishTerms':['robot de cocina','cocina inteligente'],
    'ecommerceTerms':["Ninja Foodi 14-in-1 8-qt. XL","Magimix Cook Expert"],
    'commonSearchPhrases':['robot cocina precio','ninja foodi comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'vaporera_comida', 'productName':'Vaporera / Food Steamer / Olla de Vapor', 'categoryId':'home_kitchen_appliances',
    'aliases':['vaporera','food steamer','olla de vapor','bamboo steamer'],
    'misspellings':['vaporera de comida'],
    'englishTerms':['food steamer','electric steamer','bamboo steamer set'],
    'spanishTerms':['vaporera','cocedor al vapor'],
    'ecommerceTerms':['Hamilton Beach Digital 2-Tier Steamer','COMFEE 6.5QT Steamer'],
    'commonSearchPhrases':['vaporera precio','food steamer comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'tabla_madera_corte', 'productName':'Tabla de Cortar Madera / Cutting Board / Teak', 'categoryId':'home_kitchen_appliances',
    'aliases':['tabla de cortar madera','cutting board','tabla teak','chopping board'],
    'misspellings':['tabla de cortar'],
    'englishTerms':['wood cutting board','teak cutting board','large chopping board'],
    'spanishTerms':['tabla de cortar','tabla de madera para cortar'],
    'ecommerceTerms':["Teakhaus Wood Cutting Board","OXO Good Grips Plastic Cutting Board"],
    'commonSearchPhrases':['tabla de cortar precio','cutting board comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE SPORTS ════════════════════════════════════════════════════════════
  { 'productKey':'pelota_futbol', 'productName':'Pelota de Fútbol / Adidas Brazuca / Nike', 'categoryId':'sports_fitness_physical',
    'aliases':['pelota fútbol','balón fútbol','adidas brazuca','nike football'],
    'misspellings':['pelota de futbol'],
    'englishTerms':['soccer ball','adidas tiro league ball'],
    'spanishTerms':['balón de fútbol','pelota de fútbol'],
    'ecommerceTerms':['Adidas Tiro League Soccer Ball','Nike Flight Soccer Ball'],
    'commonSearchPhrases':['pelota fútbol precio','balón adidas comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'patines_inline', 'productName':'Patines en Línea / Rollerblade / Quad Skates', 'categoryId':'sports_outdoor_variable',
    'aliases':['patines en línea','rollerblade','inline skates','quad skates'],
    'misspellings':['patines en linea'],
    'englishTerms':['inline skates','rollerblade','quad roller skates'],
    'spanishTerms':['patines en línea','patines quad'],
    'ecommerceTerms':['Rollerblade Macroblade 84','Impala Quad Roller Skate'],
    'commonSearchPhrases':['patines precio','rollerblade comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cuerda_escalar', 'productName':'Cuerda de Escalar / Arnés / Mosquetón', 'categoryId':'sports_outdoor_variable',
    'aliases':['cuerda escalar','arnés escalada','mosquetón','climbing rope'],
    'misspellings':['cuerda de escalar'],
    'englishTerms':['climbing rope dynamic','harness climbing','carabiner'],
    'spanishTerms':['cuerda de escalar','arnés de escalada'],
    'ecommerceTerms':["Black Diamond 9.6mm Dry Rock Rope","Petzl Sama Harness"],
    'commonSearchPhrases':['cuerda escalar precio','arnés escalada comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'raqueta_padel', 'productName':'Raqueta de Pádel / Bullpadel / Nox', 'categoryId':'sports_fitness_physical',
    'aliases':['raqueta padel','bullpadel','nox padel','head padel','padel racket'],
    'misspellings':['raqueta de pádel'],
    'englishTerms':['padel racket','bullpadel vertex','nox ml10'],
    'spanishTerms':['raqueta de pádel'],
    'ecommerceTerms':['Bullpadel Vertex 03 Hybrid','NOX ML10 Shotgun'],
    'commonSearchPhrases':['raqueta pádel precio','bullpadel comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'colchoneta_piscina', 'productName':'Flotador / Colchoneta Piscina / Pool Float', 'categoryId':'sports_outdoor_variable',
    'aliases':['flotador piscina','colchoneta piscina','pool float','inflable piscina'],
    'misspellings':['flotador de piscina'],
    'englishTerms':['pool float','inflatable pool lounge'],
    'spanishTerms':['flotador de piscina','colchoneta inflable'],
    'ecommerceTerms':["Intex Mega Chill Inflatable Floating Cooler","SunSplash Pool Float"],
    'commonSearchPhrases':['flotador piscina precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'guantes_pesas', 'productName':'Guantes para Pesas / Gym Gloves / Straps', 'categoryId':'sports_fitness_physical',
    'aliases':['guantes pesas','gym gloves','lifting straps','grip gloves'],
    'misspellings':['guantes para el gym'],
    'englishTerms':['weight lifting gloves','lifting straps','gym grip pads'],
    'spanishTerms':['guantes para pesas','straps de pesas'],
    'ecommerceTerms':['Harbinger Pro Wrist-Wrap Weightlifting Gloves','Bear KompleX Hand Grips'],
    'commonSearchPhrases':['guantes pesas precio','lifting straps comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE BABY ══════════════════════════════════════════════════════════════
  { 'productKey':'pañales_importados', 'productName':'Pañales / Diapers / Huggies / Pampers Premium', 'categoryId':'baby_items',
    'aliases':['pañales importados','huggies premium','pampers pure','diapers newborn'],
    'misspellings':['pañales premium'],
    'englishTerms':['diapers','huggies special delivery','pampers pure'],
    'spanishTerms':['pañales','pañales premium'],
    'ecommerceTerms':["Huggies Special Delivery Diapers","Pampers Pure Protection Diapers"],
    'commonSearchPhrases':['pañales importados precio','pampers pure comprar'],
    'riskOverrideFlags':['food_adjacent'],
    'customerHint':'Los artículos de higiene para bebé pueden requerir validación sanitaria.',
    'adminHint':'Validar CCSS/MINSA para higiene de bebé.' },

  { 'productKey':'leche_formula', 'productName':'Fórmula / Leche de Bebé / Similac', 'categoryId':'baby_items',
    'aliases':['fórmula bebé','leche de bebé','similac','enfamil','leche maternizada'],
    'misspellings':['formula de bebe'],
    'englishTerms':["baby formula","similac advance","enfamil neuropro"],
    'spanishTerms':['fórmula para bebé','leche maternizada'],
    'ecommerceTerms':['Similac Advance Infant Formula','Enfamil NeuroPro Baby Formula'],
    'commonSearchPhrases':['fórmula bebé precio','similac comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos para bebés requieren revisión sanitaria especial.',
    'adminHint':'Validar CCSS/MINSA — alimento para bebé.' },

  { 'productKey':'juguete_musical_bebe', 'productName':'Juguete Musical Bebé / Piano Infantil', 'categoryId':'baby_items',
    'aliases':['juguete musical bebé','piano infantil','vtech baby','fisher price musical'],
    'misspellings':['juguete musical de bebe'],
    'englishTerms':['baby musical toy','vtech learn and dance piano'],
    'spanishTerms':['juguete musical para bebé','piano de juguete'],
    'ecommerceTerms':['VTech Learn & Dance Interactive Zoo','Fisher-Price Kick and Play Piano Gym'],
    'commonSearchPhrases':['juguete musical bebé precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE ELECTRONICS MISC ══════════════════════════════════════════════════
  { 'productKey':'ventilador_torre', 'productName':'Ventilador Torre / Dyson Fan / Honeywell', 'categoryId':'home_decor_storage',
    'aliases':['ventilador torre','dyson fan','honeywell tower fan','bladeless fan'],
    'misspellings':['ventilador de torre'],
    'englishTerms':['tower fan','dyson pure cool','honeywell quietset'],
    'spanishTerms':['ventilador de torre','ventilador sin aspas'],
    'ecommerceTerms':['Dyson Pure Cool TP09','Honeywell QuietSet 40-Inch Tower Fan'],
    'commonSearchPhrases':['ventilador torre precio','dyson fan comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'pesas_kettlebell_set', 'productName':'Set Kettlebells / Bumper Plates / Barbell', 'categoryId':'sports_fitness_physical',
    'aliases':['kettlebell set','bumper plates','barbell set','barra olímpica'],
    'misspellings':['kettlebell de hierro'],
    'englishTerms':['kettlebell set','bumper plate set','olympic barbell'],
    'spanishTerms':['set de kettlebells','platos bumper'],
    'ecommerceTerms':['Rep Fitness Kettlebell Set','Rogue Bumper Plates','CAP Barbell Olympic Barbell'],
    'commonSearchPhrases':['kettlebell precio','bumper plates comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el peso considerable.', 'adminHint':'Verificar peso total.' },

  { 'productKey':'patineta_skate', 'productName':'Patineta / Skateboard / Longboard', 'categoryId':'sports_outdoor_variable',
    'aliases':['patineta','skateboard','longboard','cruiser board'],
    'misspellings':['skateboard tabla'],
    'englishTerms':['skateboard','longboard','penny board'],
    'spanishTerms':['patineta','skateboard'],
    'ecommerceTerms':['Powell Golden Dragon Complete Skateboard','Loaded Boards Dervish Sama Longboard'],
    'commonSearchPhrases':['patineta precio','skateboard comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'generador_electrico', 'productName':'Generador Eléctrico Portátil / Inverter', 'categoryId':'tools_hardware_common',
    'aliases':['generador eléctrico','portable generator','inverter generator','honda generator'],
    'misspellings':['generador electrico'],
    'englishTerms':['portable inverter generator','honda eu2200i'],
    'spanishTerms':['generador portátil','planta eléctrica'],
    'ecommerceTerms':['Honda EU2200i Portable Inverter Generator','Champion 3500W Generator'],
    'commonSearchPhrases':['generador eléctrico precio','planta eléctrica comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño y peso.', 'adminHint':'Verificar peso y dimensiones.' },

  { 'productKey':'lavadora_portatil', 'productName':'Lavadora Portátil / Mini Washer / Spin Dryer', 'categoryId':'home_kitchen_appliances',
    'aliases':['lavadora portátil','mini washer','spin dryer','lavadora de mesa'],
    'misspellings':['lavadora portatil'],
    'englishTerms':['portable washing machine','mini washer','spin dryer portable'],
    'spanishTerms':['lavadora portátil','lavadora compacta'],
    'ecommerceTerms':['COMFEE Portable Washing Machine','Black+Decker Twin Tub Portable'],
    'commonSearchPhrases':['lavadora portátil precio','mini washer comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'secadora_portatil', 'productName':'Secadora Portátil / Cloth Dryer / Rack', 'categoryId':'home_kitchen_appliances',
    'aliases':['secadora portátil','portable dryer','secadora ropa pequeña'],
    'misspellings':['secadora portatil'],
    'englishTerms':['portable clothes dryer','compact dryer'],
    'spanishTerms':['secadora portátil','secadora compacta'],
    'ecommerceTerms':['ZENY Portable Compact Electric Tumble Dryer','Costway FP10039'],
    'commonSearchPhrases':['secadora portátil precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'estacion_energia', 'productName':'Estación de Energía Portátil / Jackery / EcoFlow', 'categoryId':'lithium_batteries_powerbanks',
    'aliases':['estación energía','jackery','ecoflow delta','portable power station','generador solar'],
    'misspellings':['estacion de energia'],
    'englishTerms':['portable power station','jackery explorer','ecoflow delta 2'],
    'spanishTerms':['estación de energía portátil','batería de respaldo grande'],
    'ecommerceTerms':['Jackery Explorer 1000 Pro','EcoFlow DELTA 2','Bluetti AC200P'],
    'commonSearchPhrases':['estación energía precio','jackery comprar'],
    'riskOverrideFlags':['contains_lithium_battery','dangerous_goods'],
    'customerHint':'Las estaciones de energía contienen baterías de litio grandes — pueden tener restricciones de transporte aéreo.',
    'adminHint':'Revisar capacidad Wh y normativa DG. Muy probablemente no aceptable por avión.' },

  { 'productKey':'tablet_educativa_ninos', 'productName':'Tablet Educativa Niños / Amazon Kids / LeapFrog', 'categoryId':'tablets_ereaders',
    'aliases':['tablet niños','amazon kids tablet','leapfrog','fire kids','tablet infantil'],
    'misspellings':['tablet educativa niños'],
    'englishTerms':['kids tablet','amazon fire kids','leapfrog epic academy'],
    'spanishTerms':['tablet para niños','tablet educativa'],
    'ecommerceTerms':['Amazon Fire HD 8 Kids Tablet','LeapFrog LeapPad Academy'],
    'commonSearchPhrases':['tablet niños precio','amazon fire kids comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'teclado_piano_midi', 'productName':'Teclado MIDI / Piano Digital / Yamaha P', 'categoryId':'microphones_audio_pro',
    'aliases':['teclado midi','piano digital','yamaha p145','roland fp30','midi keyboard'],
    'misspellings':['teclado MIDI piano'],
    'englishTerms':['midi keyboard','yamaha p-145 digital piano','roland fp-30x'],
    'spanishTerms':['piano digital','teclado midi'],
    'ecommerceTerms':['Yamaha P-145 Digital Piano','Roland FP-30X Digital Piano','Arturia MiniLab 3'],
    'commonSearchPhrases':['piano digital precio','teclado midi comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el peso.', 'adminHint':'Verificar peso.' },

  { 'productKey':'bateria_aaa_aa', 'productName':'Baterías AA / AAA / 9V / Recargables', 'categoryId':'chargers_cables_adapters',
    'aliases':['baterías aa','baterías aaa','baterías recargables','eneloop','duracell'],
    'misspellings':['baterias recargables'],
    'englishTerms':['rechargeable batteries aa','eneloop pro','duracell batteries'],
    'spanishTerms':['pilas recargables','baterías aa'],
    'ecommerceTerms':['Panasonic eneloop pro AA 4-Pack','Duracell Optimum AA 12-Pack'],
    'commonSearchPhrases':['pilas recargables precio','eneloop comprar'],
    'riskOverrideFlags':['contains_lithium_battery'],
    'customerHint':'Las baterías de litio pueden requerir revisión adicional para transporte.',
    'adminHint':'Revisar tipo y restricciones.' },

  # ══ MORE BEAUTY — NAIL / SPA ═══════════════════════════════════════════════
  { 'productKey':'bano_pies_electrico', 'productName':'Baño de Pies Eléctrico / Foot Spa / Masajeador', 'categoryId':'beauty_devices',
    'aliases':['baño pies eléctrico','foot spa','masajeador pies','foot massager'],
    'misspellings':['baño de pies electrico'],
    'englishTerms':['electric foot spa','foot massager bath'],
    'spanishTerms':['baño de pies eléctrico','masajeador de pies'],
    'ecommerceTerms':['Conair Waterfall Foot Spa','HOMEDICS Foot Spa'],
    'commonSearchPhrases':['baño pies eléctrico precio','foot spa comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'epiladora_depilacion', 'productName':'Epiladora Eléctrica / Wax Kit / Depilación', 'categoryId':'beauty_devices',
    'aliases':['epiladora eléctrica','wax kit','depilación cera','epilator braun'],
    'misspellings':['epiladora electrica'],
    'englishTerms':['epilator','waxing kit','braun epilator'],
    'spanishTerms':['epiladora','kit de depilación con cera'],
    'ecommerceTerms':['Braun Silk-épil 9 Epilator','WAXKISS Professional Waxing Kit'],
    'commonSearchPhrases':['epiladora precio','wax kit comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'corrector_postura', 'productName':'Corrector de Postura / Back Brace / Lumbar', 'categoryId':'medicines_medical_products',
    'aliases':['corrector postura','back brace','faja lumbar','posture corrector'],
    'misspellings':['corrector de postura'],
    'englishTerms':['posture corrector','lumbar back brace','posture support'],
    'spanishTerms':['corrector de postura','faja lumbar'],
    'ecommerceTerms':["ComfyBrace Posture Corrector","Mueller Lumbar Support Back Brace"],
    'commonSearchPhrases':['corrector postura precio','faja lumbar comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  # ══ MORE FOOD / BEVERAGES ══════════════════════════════════════════════════
  { 'productKey':'energy_drink', 'productName':'Bebida Energizante / Ghost / Prime / C4', 'categoryId':'food_beverages_review',
    'aliases':['bebida energizante','ghost energy','prime hydration','c4 energy drink'],
    'misspellings':['bebida energética'],
    'englishTerms':['energy drink','ghost energy','prime hydration drink'],
    'spanishTerms':['bebida energizante','bebida deportiva'],
    'ecommerceTerms':['Ghost Energy Drink Case','Prime Hydration Variety Pack','C4 Energy Carbonated'],
    'commonSearchPhrases':['ghost energy precio','prime drink comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos importados pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA/MINSA.' },

  { 'productKey':'chocolate_fino', 'productName':'Chocolate Fino / Belga / Lindt / Godiva', 'categoryId':'food_beverages_review',
    'aliases':['chocolate belga','lindt chocolate','godiva','chocolate gourmet'],
    'misspellings':['chocolate fino belga'],
    'englishTerms':['belgian chocolate','godiva gift box','lindt lindor'],
    'spanishTerms':['chocolate fino','chocolates de regalo'],
    'ecommerceTerms':['Godiva Chocolatier Gift Box','Lindt Excellence Dark Chocolate Bar'],
    'commonSearchPhrases':['chocolate belga precio','godiva comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos importados pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA/MINSA.' },

  { 'productKey':'te_importado', 'productName':'Té Importado / Organic / Sencha / Oolong', 'categoryId':'food_beverages_review',
    'aliases':['té importado','té orgánico','sencha','oolong','puerh tea'],
    'misspellings':['te organico importado'],
    'englishTerms':['organic green tea','oolong tea','premium loose leaf tea'],
    'spanishTerms':['té orgánico','té importado'],
    'ecommerceTerms':["Ippodo Yame Gyokuro","Harney & Sons Hot Cinnamon Spice"],
    'commonSearchPhrases':['té orgánico precio','oolong comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos importados pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA/MINSA.' },

  { 'productKey':'aceite_cocina_importado', 'productName':'Aceite de Cocina / Oliva / Aguacate / MCT', 'categoryId':'food_beverages_review',
    'aliases':['aceite de oliva','aceite aguacate','mct oil','olive oil importado'],
    'misspellings':['aceite de oliva importado'],
    'englishTerms':["extra virgin olive oil","avocado oil","mct oil"],
    'spanishTerms':['aceite de oliva','aceite de aguacate'],
    'ecommerceTerms':["California Olive Ranch EVOO","Chosen Foods 100% Pure Avocado Oil"],
    'commonSearchPhrases':['aceite de oliva precio','aceite aguacate comprar'],
    'riskOverrideFlags':['food','sanitary_review'],
    'customerHint':'Los alimentos importados pueden requerir revisión sanitaria.',
    'adminHint':'Validar SENASA/MINSA.' },

  # ══ MORE REGULATED ════════════════════════════════════════════════════════
  { 'productKey':'medicamento_otc', 'productName':'Medicamento OTC / Ibuprofen / Vitamina D Rx', 'categoryId':'medicines_medical_products',
    'aliases':['medicamento otc','ibuprofen','tylenol','allergy medicine','antihistamine'],
    'misspellings':['medicamento OTC'],
    'englishTerms':['otc medication','ibuprofen','allergy medicine'],
    'spanishTerms':['medicamento sin receta','ibuprofeno importado'],
    'ecommerceTerms':["Advil Ibuprofen 200mg 300ct","Claritin 24 Hour Non-Drowsy Allergy"],
    'commonSearchPhrases':['ibuprofeno importado precio'],
    'riskOverrideFlags':['medical','sanitary_review'],
    'customerHint':'Los medicamentos importados requieren revisión sanitaria y pueden necesitar receta médica.',
    'adminHint':'Revisar CCSS/MINSA — medicamentos con o sin receta.' },

  { 'productKey':'aceite_cbd', 'productName':'Aceite CBD / Hemp / Cannabidiol', 'categoryId':'alcohol_tobacco_vape_review',
    'aliases':['aceite cbd','cbd oil','hemp oil','cannabidiol','cbd gummies'],
    'misspellings':['acite cbd'],
    'englishTerms':['cbd oil','hemp extract','cbd gummies'],
    'spanishTerms':['aceite de cbd','cáñamo cbd'],
    'ecommerceTerms':["Charlotte's Web CBD Oil","CBDistillery Full Spectrum CBD Oil"],
    'commonSearchPhrases':['aceite cbd precio','cbd oil comprar'],
    'riskOverrideFlags':['controlled_substance_possible','restricted_possible'],
    'customerHint':'El CBD puede estar restringido en Costa Rica — requiere revisión especial.',
    'adminHint':'Revisar normativa nacional para CBD/cannabidiol.' },

  { 'productKey':'gas_butano', 'productName':'Gas Butano / Cilindro / Camping Gas', 'categoryId':'dangerous_goods',
    'aliases':['gas butano','camping gas','gas canister','gas isobutano'],
    'misspellings':['gas butano camping'],
    'englishTerms':['butane gas canister','camping fuel','isobutane canister'],
    'spanishTerms':['gas butano','cilindro de gas para camping'],
    'ecommerceTerms':['MSR IsoPro Canister Fuel','Snow Peak GigaPower Fuel'],
    'commonSearchPhrases':['gas butano precio','camping gas comprar'],
    'riskOverrideFlags':['dangerous_goods','flammable','special_transport'],
    'customerHint':'Este producto es inflamable y tiene restricciones especiales de transporte.',
    'adminHint':'Revisar normativa DG — gas inflamable.' },

  { 'productKey':'planta_viva', 'productName':'Planta Viva / Suculenta / Cactus / Tropical', 'categoryId':'plants_seeds_agro_review',
    'aliases':['planta viva','suculenta','cactus','monstera','planta tropical importada'],
    'misspellings':['planta viva importada'],
    'englishTerms':['live plant','succulent','cactus','tropical plant'],
    'spanishTerms':['planta viva','suculenta importada'],
    'ecommerceTerms':['Costa Farms Monstera Deliciosa','Rooted Succulent Collection'],
    'commonSearchPhrases':['planta viva precio','suculenta comprar'],
    'riskOverrideFlags':['agro','phytosanitary_review'],
    'customerHint':'Las plantas vivas requieren revisión fitosanitaria obligatoria para ingresar a Costa Rica.',
    'adminHint':'Validar SFE/SENASA — fitosanitario obligatorio para plantas vivas.' },

  # ══ MORE GAMING & STREAMING ════════════════════════════════════════════════
  { 'productKey':'streaming_deck_elgato', 'productName':'Stream Deck / Elgato / Macro Pad', 'categoryId':'gaming_physical_accessories',
    'aliases':['stream deck','elgato stream deck','macro pad','control panel streaming'],
    'misspellings':['elgato stream deck'],
    'englishTerms':['elgato stream deck mk.2','stream deck mini'],
    'spanishTerms':['stream deck','panel de control streaming'],
    'ecommerceTerms':['Elgato Stream Deck MK.2','Elgato Stream Deck Mini'],
    'commonSearchPhrases':['stream deck precio','elgato deck comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'llave_seguridad', 'productName':'Llave de Seguridad / Cerradura Inteligente / Smart Lock', 'categoryId':'networking_equipment',
    'aliases':['cerradura inteligente','smart lock','schlage encode','august lock'],
    'misspellings':['smart lock inteligente'],
    'englishTerms':['smart lock','schlage encode','august wifi smart lock'],
    'spanishTerms':['cerradura inteligente','candado smart'],
    'ecommerceTerms':['Schlage Encode Plus Smart WiFi Deadbolt','August Wi-Fi Smart Lock'],
    'commonSearchPhrases':['cerradura inteligente precio','smart lock comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cargador_bicicleta_electrica', 'productName':'Cargador Bicicleta Eléctrica / Scooter Eléctrico', 'categoryId':'chargers_cables_adapters',
    'aliases':['cargador ebike','scooter eléctrico cargador','e-bike charger'],
    'misspellings':['cargador de ebike'],
    'englishTerms':['ebike charger','electric scooter charger'],
    'spanishTerms':['cargador para bicicleta eléctrica','cargador scooter'],
    'ecommerceTerms':["Rad Power Bikes RadRunner Charger","Xiaomi Electric Scooter Charger"],
    'commonSearchPhrases':['cargador ebike precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'scooter_electrico', 'productName':'Scooter Eléctrico / Patineta Eléctrica / Xiaomi', 'categoryId':'sports_outdoor_variable',
    'aliases':['scooter eléctrico','patineta eléctrica','xiaomi scooter','ninebot segway'],
    'misspellings':['scooter electrico'],
    'englishTerms':['electric scooter','xiaomi mi electric scooter'],
    'spanishTerms':['scooter eléctrico','patineta eléctrica'],
    'ecommerceTerms':['Xiaomi Electric Scooter 4 Pro','Segway Ninebot KickScooter MAX G30LP'],
    'commonSearchPhrases':['scooter eléctrico precio','xiaomi scooter comprar'],
    'riskOverrideFlags':['contains_lithium_battery'],
    'customerHint':'Los scooters eléctricos contienen baterías de litio — pueden tener restricciones de transporte.',
    'adminHint':'Revisar normativa DG y Wh de la batería.' },

  # ══ ADDITIONAL MISC ROWS ══════════════════════════════════════════════════
  { 'productKey':'tazas_mug', 'productName':'Tazas / Mug Térmico / Stanley / YETI', 'categoryId':'home_kitchen_appliances',
    'aliases':['mug térmico','stanley tumbler','yeti mug','termos café'],
    'misspellings':['stanley cup','yeti taza'],
    'englishTerms':['tumbler','stanley quencher','yeti rambler mug'],
    'spanishTerms':['vaso térmico','mug stanley'],
    'ecommerceTerms':['Stanley Quencher H2.0 40oz','YETI Rambler 20oz Mug','Hydro Flask Coffee Mug'],
    'commonSearchPhrases':['stanley tumbler precio','yeti mug comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'mochila_senderismo', 'productName':'Mochila Senderismo / Osprey / Gregory / 40L', 'categoryId':'bags_luggage_accessories',
    'aliases':['mochila senderismo','osprey','gregory backpack','hiking backpack 40l'],
    'misspellings':['mochila de senderismo'],
    'englishTerms':['hiking backpack','osprey atmos ag 65','gregory paragon 58'],
    'spanishTerms':['mochila de senderismo','mochila para montaña'],
    'ecommerceTerms':['Osprey Atmos AG 65 Backpack','Gregory Paragon 58 Backpack'],
    'commonSearchPhrases':['mochila senderismo precio','osprey backpack comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'soporte_telefono_escritorio', 'productName':'Soporte Celular Escritorio / Magnetic Stand', 'categoryId':'computer_accessories',
    'aliases':['soporte celular escritorio','phone stand','magnetic phone stand','desk phone holder'],
    'misspellings':['soporte de celular escritorio'],
    'englishTerms':['phone desk stand','magnetic phone holder desktop'],
    'spanishTerms':['soporte de celular','sostenedor para celular'],
    'ecommerceTerms':['Lamicall Phone Stand','Anker 3-in-1 MagSafe Charging Stand'],
    'commonSearchPhrases':['soporte celular escritorio precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'teclado_gaming_rgb', 'productName':'Teclado RGB / Hotswap / Corsair / Ducky', 'categoryId':'computer_accessories',
    'aliases':['teclado rgb','hotswap keyboard','corsair k70','ducky one 3','keychron q'],
    'misspellings':['teclado rgb gaming'],
    'englishTerms':['rgb gaming keyboard','hot-swap keyboard','corsair k70 rgb'],
    'spanishTerms':['teclado gamer rgb','teclado mecánico rgb'],
    'ecommerceTerms':['Corsair K70 RGB Pro','Ducky One 3 TKL','Keychron Q1 Pro'],
    'commonSearchPhrases':['teclado rgb precio','corsair k70 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cámara_espejo_dslr', 'productName':'Cámara DSLR / Reflex / Canon EOS / Nikon D', 'categoryId':'cameras_photo_video',
    'aliases':['cámara dslr','cámara reflex','canon eos rebel','nikon d3500','nikon d7500'],
    'misspellings':['cámara réflex'],
    'englishTerms':['dslr camera','canon eos rebel t8i','nikon d7500'],
    'spanishTerms':['cámara réflex','cámara dslr'],
    'ecommerceTerms':['Canon EOS Rebel T8i DSLR','Nikon D3500 DSLR Camera'],
    'commonSearchPhrases':['cámara dslr precio','canon rebel comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'bateria_laptop', 'productName':'Batería de Laptop / Reemplazo / OEM', 'categoryId':'lithium_batteries_powerbanks',
    'aliases':['batería laptop','laptop battery replacement','batería de repuesto laptop'],
    'misspellings':['bateria de laptop'],
    'englishTerms':['laptop replacement battery','oem laptop battery'],
    'spanishTerms':['batería de repuesto para laptop'],
    'ecommerceTerms':["Anker 45W Laptop Battery Replacement","Lenovo ThinkPad Battery"],
    'commonSearchPhrases':['batería laptop repuesto precio'],
    'riskOverrideFlags':['contains_lithium_battery'],
    'customerHint':'Las baterías de litio pueden requerir revisión adicional para transporte.',
    'adminHint':'Revisar capacidad Wh y normativa de transporte.' },

  { 'productKey':'smart_tv_box', 'productName':'Android TV Box / NVIDIA Shield / Apple TV', 'categoryId':'tv_projectors_streaming',
    'aliases':['android tv box','nvidia shield','apple tv','kodi box','tv stick android'],
    'misspellings':['android tv stick'],
    'englishTerms':['android tv box','nvidia shield pro','google tv dongle'],
    'spanishTerms':['caja android tv','decodificador android'],
    'ecommerceTerms':['NVIDIA Shield TV Pro','Google Chromecast with Google TV 4K','Formuler Z11 Pro Max'],
    'commonSearchPhrases':['android tv box precio','nvidia shield comprar'],
    'riskOverrideFlags':['telecom_possible'], 'customerHint':'', 'adminHint':'Verificar homologación SUTEL.' },

  { 'productKey':'selfie_stick', 'productName':'Selfie Stick / Palo Selfie / Trípode Portátil', 'categoryId':'cameras_photo_video',
    'aliases':['selfie stick','palo selfie','selfie palo','mini tripod phone'],
    'misspellings':['palo de selfie'],
    'englishTerms':['selfie stick','mini tripod selfie'],
    'spanishTerms':['palo de selfie','palo para fotos'],
    'ecommerceTerms':['GorillaPod Mini Tripod','UBeesize Phone Tripod with Remote'],
    'commonSearchPhrases':['selfie stick precio','palo selfie comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'pantallas_acrilico', 'productName':'Pantalla Acrílica / Separador / Desk Divider', 'categoryId':'office_stationery_art',
    'aliases':['pantalla acrílica','desk divider','separador escritorio','office partition'],
    'misspellings':['pantalla acrilica'],
    'englishTerms':['acrylic desk divider','desk partition screen'],
    'spanishTerms':['pantalla de escritorio','separador de oficina'],
    'ecommerceTerms':['Luxor Acrylic Desktop Divider','Fab Glass Acrylic Sneeze Guard'],
    'commonSearchPhrases':['separador escritorio precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'caja_herramientas', 'productName':'Caja de Herramientas / Tool Chest / Stanley', 'categoryId':'tools_hardware_common',
    'aliases':['caja herramientas','tool chest','caja stanley','tool box'],
    'misspellings':['caja de herramientas'],
    'englishTerms':['tool chest','stanley tool box','portable tool storage'],
    'spanishTerms':['caja de herramientas','maletín de herramientas'],
    'ecommerceTerms':["Stanley FatMax Tool Chest","Husky 46 in. 9-Drawer Mobile Workbench"],
    'commonSearchPhrases':['caja herramientas precio','tool chest comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el peso.', 'adminHint':'Verificar peso.' },

  { 'productKey':'detector_metales', 'productName':'Detector de Metales / Garrett / Minelab', 'categoryId':'tools_hardware_common',
    'aliases':['detector metales','metal detector','garrett ace','minelab equinox'],
    'misspellings':['detector de metales'],
    'englishTerms':['metal detector','garrett ace 400','minelab equinox 800'],
    'spanishTerms':['detector de metales'],
    'ecommerceTerms':['Garrett ACE 400 Metal Detector','Minelab EQUINOX 800'],
    'commonSearchPhrases':['detector metales precio','garrett ace comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'termo_stanley', 'productName':'Termo / Stanley / YETI / Camelbak', 'categoryId':'home_kitchen_appliances',
    'aliases':['termo stanley','yeti rambler','camelbak insulated','thermos bottle'],
    'misspellings':['termo stanley cup'],
    'englishTerms':['insulated water bottle','stanley classic bottle','yeti rambler 36oz'],
    'spanishTerms':['termo','botella térmica'],
    'ecommerceTerms':['Stanley Classic Legendary Bottle 1.5qt','YETI Rambler 36oz Bottle','Hydro Flask 32oz Wide Mouth'],
    'commonSearchPhrases':['termo stanley precio','yeti rambler comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'maletin_cuero', 'productName':'Maletín de Cuero / Laptop Bag Formal', 'categoryId':'bags_luggage_accessories',
    'aliases':['maletín cuero','leather briefcase','laptop bag formal','maletín ejecutivo'],
    'misspellings':['maletin de cuero'],
    'englishTerms':['leather briefcase','laptop messenger bag'],
    'spanishTerms':['maletín de cuero','maletín ejecutivo'],
    'ecommerceTerms':["Samsonite Classic Business Slim Briefcase","Tumi Alpha 3 Briefcase"],
    'commonSearchPhrases':['maletín cuero precio','leather briefcase comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'cuaderno_leuchtturm', 'productName':'Cuaderno Leuchtturm / Moleskine / Rhodia', 'categoryId':'office_stationery_art',
    'aliases':['cuaderno leuchtturm','moleskine','rhodia','libreta premium'],
    'misspellings':['cuaderno moleskine'],
    'englishTerms':['leuchtturm1917 notebook','moleskine classic notebook'],
    'spanishTerms':['cuaderno leuchtturm','libreta moleskine'],
    'ecommerceTerms':['Leuchtturm1917 Medium A5 Hardcover Notebook','Moleskine Classic Ruled Notebook'],
    'commonSearchPhrases':['moleskine precio','leuchtturm1917 comprar'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'collar_cuero_perro', 'productName':'Collar de Cuero / Personalizado / Luxury Pet', 'categoryId':'pet_accessories',
    'aliases':['collar cuero perro','luxury pet collar','personalizado collar mascota'],
    'misspellings':['collar de cuero para perro'],
    'englishTerms':['leather dog collar','personalized pet collar'],
    'spanishTerms':['collar de cuero para perro','collar personalizado'],
    'ecommerceTerms':["Orvis Personalized Dog Collar","Soft Touch Collars Leather Collar"],
    'commonSearchPhrases':['collar cuero perro precio'],
    'riskOverrideFlags':[], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'gafas_vr', 'productName':'Gafas VR / Meta Quest / PlayStation VR', 'categoryId':'gaming_consoles_electronics',
    'aliases':['gafas vr','meta quest','psvr2','oculus quest','realidad virtual'],
    'misspellings':['gafas de realidad virtual'],
    'englishTerms':['vr headset','meta quest 3','psvr2'],
    'spanishTerms':['gafas de realidad virtual','visor vr'],
    'ecommerceTerms':['Meta Quest 3 128GB','PlayStation VR2'],
    'commonSearchPhrases':['meta quest 3 precio','vr headset comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'auriculares_sony_ze', 'productName':'Sony LinkBuds / WF-1000XM5 / Inear', 'categoryId':'headphones_audio_personal',
    'aliases':['sony linkbuds','sony wf 1000xm5','sony inear','sony truly wireless'],
    'misspellings':['sony wf1000xm5'],
    'englishTerms':['sony wf-1000xm5','sony linkbuds s'],
    'spanishTerms':['audífonos sony inalámbricos','sony wf'],
    'ecommerceTerms':['Sony WF-1000XM5 True Wireless','Sony LinkBuds S'],
    'commonSearchPhrases':['sony wf1000xm5 precio','sony linkbuds comprar'],
    'riskOverrideFlags':['battery_possible'], 'customerHint':'', 'adminHint':'' },

  { 'productKey':'mini_frigorifico', 'productName':'Mini Refrigerador / Fridge / Beverage Cooler', 'categoryId':'home_kitchen_appliances',
    'aliases':['mini refrigerador','mini fridge','beverage cooler','pequeño refrigerador'],
    'misspellings':['mini refrigerador'],
    'englishTerms':['mini fridge','compact refrigerator','beverage cooler'],
    'spanishTerms':['mini refrigerador','frigobar'],
    'ecommerceTerms':['Frigidaire EFMIS129 Mini Portable Compact Personal Fridge','hOmeLabs Beverage Refrigerator'],
    'commonSearchPhrases':['mini fridge precio','frigobar comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño y peso.', 'adminHint':'Verificar dimensiones y peso.' },

  { 'productKey':'silla_escritorio_basica', 'productName':'Silla de Escritorio / Task Chair / Office Depot', 'categoryId':'office_stationery_art',
    'aliases':['silla escritorio','task chair','silla de oficina básica','office chair'],
    'misspellings':['silla de escritorio'],
    'englishTerms':['office desk chair','task chair','computer chair'],
    'spanishTerms':['silla de escritorio','silla de oficina'],
    'ecommerceTerms':["Amazon Basics Ergonomic Adjustable Chair","HON Ignition Task Chair"],
    'commonSearchPhrases':['silla escritorio precio','office chair comprar'],
    'riskOverrideFlags':[], 'customerHint':'El cálculo puede variar por el tamaño.', 'adminHint':'Verificar dimensiones.' },

]

# ── Insert into JS ────────────────────────────────────────────────────────────

JS_MARKER = '    // ════════════════ TASK #384 EXPANSION BATCH 2 ════════════════'

with open('js/product-categories.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

insert_pos = js_content.find(JS_MARKER)
if insert_pos == -1:
    print('ERROR: JS marker not found', file=sys.stderr); sys.exit(1)

new_js_block = '\n    // ════════════════ TASK #384 EXPANSION BATCH 3 ════════════════\n'
new_js_block += '\n'.join(row_to_js(r) for r in BATCH3)
new_js_block += '\n'

js_new = js_content[:insert_pos] + new_js_block + js_content[insert_pos:]

with open('js/product-categories.js', 'w', encoding='utf-8') as f:
    f.write(js_new)

print(f'JS: inserted {len(BATCH3)} rows in batch 3')

# ── Insert into JSON ──────────────────────────────────────────────────────────

with open('data/product-brain.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

for r in BATCH3:
    row = {
        'productKey': r['productKey'], 'productName': r['productName'],
        'categoryId': r['categoryId'],
        'aliases': r.get('aliases',[]), 'misspellings': r.get('misspellings',[]),
        'englishTerms': r.get('englishTerms',[]), 'spanishTerms': r.get('spanishTerms',[]),
        'ecommerceTerms': r.get('ecommerceTerms',[]),
        'commonSearchPhrases': r.get('commonSearchPhrases',[]),
        'riskOverrideFlags': r.get('riskOverrideFlags',[]),
        'customerHint': r.get('customerHint',''), 'adminHint': r.get('adminHint',''),
    }
    json_data['products'].append(row)

with open('data/product-brain.json', 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f'JSON: now has {len(json_data["products"])} products, {len(json_data["categories"])} categories')
